#######################################################
# 
# BaseWork.py
# Python implementation of the Class BaseWork
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:19 PM
# Original author: T. Kostic
# 
#######################################################
from IEC61968 import WorkActivityRecord
from IEC61968 import WorkLocation
from java.IEC61968.Work import WorkTimeSchedule
from java.IEC61968.Common import Document

class BaseWork(Document):
    """Common representation for work and work tasks.
    """
    # All activity records for this work or work task.
    WorkActivityRecords= WorkActivityRecord()

    # Location for this work/task.
    WorkLocation= WorkLocation()

    # All time schedules for this work or work task.
    TimeSchedules= WorkTimeSchedule()
