#######################################################
# 
# MaterialItem.py
# Python implementation of the Class MaterialItem
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:22 PM
# 
#######################################################
from IEC61970.Base.Domain.IntegerQuantity import IntegerQuantity
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class MaterialItem(IdentifiedObject):
    """The physical consumable supply used for work and other purposes. It includes
    items such as nuts, bolts, brackets, glue, etc.
    """
    pass
