#######################################################
# 
# WorkLocation.py
# Python implementation of the Class WorkLocation
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:26 PM
# 
#######################################################
from IEC61968 import OneCallRequest
from java.IEC61968.Common import Location

class WorkLocation(Location):
    """Information about a particular location for various forms of work.
    """
    OneCallRequest= OneCallRequest()
