#######################################################
# 
# WorkActivityRecord.py
# Python implementation of the Class WorkActivityRecord
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:26 PM
# 
#######################################################
from IEC61968 import ActivityRecord

class WorkActivityRecord(ActivityRecord):
    """Records information about the status of work or work task at a point in time.
    """
    pass
