#######################################################
# 
# DCLineSegment.py
# Python implementation of the Class DCLineSegment
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 9:03:42 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Capacitance import Capacitance
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Inductance import Inductance
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Length import Length
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Resistance import Resistance
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.DC.DCConductingEquipment import DCConductingEquipment

class DCLineSegment(DCConductingEquipment):
    """A wire or combination of wires not insulated from one another, with consistent
    electrical characteristics, used to carry direct current between points in the
    DC region of the power system.
    """
    def __init__(self):
        super().__init__()
        self.resistance: Resistance = Resistance()
        self.capacitance: Capacitance = Capacitance()
        self.length: Length = Length()
        self.inductance: Inductance = Inductance()
