#######################################################
# 
# EndDeviceFunction.py
# Python implementation of the Class EndDeviceFunction
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 9:29:33 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61968.Assets.AssetFunction import AssetFunction


class EndDeviceFunction(AssetFunction):
    """Function performed by an end device such as a meter, communication equipment,
    controllers, etc.
    """
    def __init__(self):
        super().__init__()
        self.enabled = False
