package IEC62325.MarketOperations.MktDomain;


/**
 * For example:
 * DEFAULT_ENERGY_BID
 * DEFAULT_STARTUP_BID
 * DEFAULT_MINIMUM_LOAD_BID
 * @created 03-Jan-2024 2:12:37 PM
 */
public enum BidType {
	DEFAULT_ENERGY_BID,
	DEFAULT_STARTUP_BID,
	DEFAULT_MINIMUM_LOAD_BID
}