#######################################################
# 
# LimitDependency.py
# Python implementation of the Class LimitDependency
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:15:36 PM
# Original author: akamath
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject


class LimitDependency(IdentifiedObject):
    """A limit calculation model used to compute an operational limit based on
    external input such as temperature. These are intended to be shared among
    operational limits with the same calculation form that apply to a piece of
    equipment..
    """
    def __init__(self):
        super().__init__()

