#######################################################
# 
# CableInfo.py
# Python implementation of the Class CableInfo
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 11:00:09 AM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61968.AssetInfo.CableConstructionKind import CableConstructionKind
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Length import Length
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Temperature import Temperature
from CIM_STD_PYTHON.TC57CIM.IEC61968.AssetInfo.CableOuterJacketKind import CableOuterJacketKind
from CIM_STD_PYTHON.TC57CIM.IEC61968.AssetInfo.CableShieldMaterialKind import CableShieldMaterialKind
from CIM_STD_PYTHON.TC57CIM.IEC61968.AssetInfo.WireInfo import WireInfo

class CableInfo(WireInfo):
    """Cable data.
    """
    def __init__(self):
        super().__init__()
        self.construction_kind = CableConstructionKind.SOLID
        self.diameter_over_core = Length()
        self.diameter_over_insulation = Length()
        self.diameter_over_jacket = Length()
        self.diameter_over_screen = Length()
        self.is_strand_fill = True
        self.nominal_temperature = Temperature()
        self.outer_jacket_kind = CableOuterJacketKind.PVC
        self.sheath_as_neutral = True
        self.shield_material = CableShieldMaterialKind.STEEL