#######################################################
# 
# WireInfo.py
# Python implementation of the Class WireInfo
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 11:02:34 AM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Length import Length
from CIM_STD_PYTHON.TC57CIM.IEC61968.AssetInfo.WireInsulationKind import WireInsulationKind
from CIM_STD_PYTHON.TC57CIM.IEC61968.AssetInfo.WireMaterialKind import WireMaterialKind
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.ResistancePerLength import ResistancePerLength
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.CurrentFlow import CurrentFlow
from CIM_STD_PYTHON.TC57CIM.IEC61968.AssetInfo.WirePhaseInfo import WirePhaseInfo
from CIM_STD_PYTHON.TC57CIM.IEC61968.Assets.AssetInfo import AssetInfo

class WireInfo(AssetInfo):
    """Wire data that can be specified per line segment phase, or for the line segment
    as a whole in case its phases all have the same wire characteristics.
    """
    def __init__(self):
        super().__init__()
        self.core_radius = Length()
        self.core_strand_count = 0
        self.gmr = Length()
        self.insulated = True
        self.insulation_material = WireInsulationKind.OTHER
        self.insulation_thickness = Length()
        self.material = WireMaterialKind.STEEL
        self.rAC25 = ResistancePerLength()
        self.rAC50 = ResistancePerLength()
        self.rAC75 = ResistancePerLength()
        self.radius = Length()
        self.rated_current = CurrentFlow()
        self.rDC20 = ResistancePerLength()
        self.size_description = ""
        self.strand_count = 0
        self.wire_phase_info = WirePhaseInfo()