#######################################################
# 
# WireInfo.py
# Python implementation of the Class WireInfo
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 11:02:34 AM
# 
#######################################################
from IEC61970.Base.Domain.Length import Length
from IEC61968.AssetInfo.WireInsulationKind import WireInsulationKind
from IEC61968.AssetInfo.WireMaterialKind import WireMaterialKind
from IEC61970.Base.Domain.ResistancePerLength import ResistancePerLength
from IEC61970.Base.Domain.CurrentFlow import CurrentFlow
from IEC61968.AssetInfo.WirePhaseInfo import WirePhaseInfo
from IEC61968.Assets.AssetInfo import AssetInfo

class WireInfo(AssetInfo):
    """Wire data that can be specified per line segment phase, or for the line segment
    as a whole in case its phases all have the same wire characteristics.
    """
    def __init__(self):
        super().__init__()
        self.core_radius = Length()  # (if there is a different core material) Radius of the central core.
        self.core_strand_count = 0  # (if used) Number of strands in the steel core.
        self.gmr = Length()  # Geometric mean radius.
        self.insulated = True  # True if conductor is insulated.
        self.insulation_material = WireInsulationKind.RUBBER  # (if insulated conductor) Material used for insulation.
        self.insulation_thickness = Length()  # (if insulated conductor) Thickness of the insulation.
        self.material = WireMaterialKind.COPPER  # Conductor material.
        self.rAC25 = ResistancePerLength()  # AC resistance per unit length of the conductor at 25 °C.
        self.rAC50 = ResistancePerLength()  # AC resistance per unit length of the conductor at 50 °C.
        self.rAC75 = ResistancePerLength()  # AC resistance per unit length of the conductor at 75 °C.
        self.radius = Length()  # Outside radius of the wire.
        self.rated_current = CurrentFlow()  # Current carrying capacity of the wire under stated thermal conditions.
        self.rDC20 = ResistancePerLength()  # DC resistance per unit length of the conductor at 20 °C.
        self.size_description = ""  # Describes the wire gauge or cross section.
        self.strand_count = 1  # Number of strands in the conductor.
        self.wire_phase_info = WirePhaseInfo()