#######################################################
# 
# TypeAssetCatalogue.py
# Python implementation of the Class TypeAssetCatalogue
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:25 PM
# 
#######################################################
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class TypeAssetCatalogue(IdentifiedObject):
    """Catalogue of generic types of assets (TypeAsset) that may be used for design
    purposes. It is not associated with a particular manufacturer.
    """
    pass
