#######################################################
# 
# AnalogValue.py
# Python implementation of the Class AnalogValue
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:54 PM
# 
#######################################################
from IEC61970.Base.Domain.Float import Float
from IEC61970.Base.Meas.MeasurementValue import MeasurementValue
from IEC61970.Base.Meas.AnalogControl import AnalogControl

class AnalogValue(MeasurementValue):
    """AnalogValue represents an analog MeasurementValue.
    """
    # The Control variable associated with the MeasurementValue.
    AnalogControl= AnalogControl()
