#######################################################
# 
# Control.py
# Python implementation of the Class Control
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:55 PM
# 
#######################################################

from IEC61970.Base.Domain.Boolean import Boolean
from IEC61970.Base.Domain.DateTime import DateTime
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Meas.IOPoint import IOPoint

class Control(IOPoint):
    """Control is used for supervisory/device control. It represents control outputs
    that are used to change the state in a process, e.g. close or open breaker, a
    set point value or a raise lower command.
    """
    pass
