#######################################################
# 
# IOPoint.py
# Python implementation of the Class IOPoint
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:59 PM
# Original author: SELAOST1
# 
#######################################################
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from IEC61970.Base.ICCPConfiguration.ProvidedBilateralPoint import ProvidedBilateralPoint

class IOPoint(IdentifiedObject):
    """The class describe a measurement or control value. The purpose is to enable
    having attributes and associations common for measurement and control.
    """
    BilateralToIOPoint= ProvidedBilateralPoint()
