#######################################################
# 
# MeasurementValueSource.py
# Python implementation of the Class MeasurementValueSource
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:00 PM
# 
#######################################################
from IEC61970.Base.Meas.MeasurementValue import MeasurementValue
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class MeasurementValueSource(IdentifiedObject):
    """MeasurementValueSource describes the alternative sources updating a
    MeasurementValue. User conventions for how to use the MeasurementValueSource
    attributes are described in the introduction to IEC 61970-301.
    """
    # The MeasurementValues updated by the source.
    MeasurementValues= MeasurementValue()
