#######################################################
# 
# ContingencyEquipmentStatusKind.py
# Python implementation of the Class ContingencyEquipmentStatusKind
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:55 PM
# Original author: kdd
# 
#######################################################


class ContingencyEquipmentStatusKind:
    """Indicates the state which the contingency equipment is to be in when the
    contingency is applied.
    """
    pass
