#######################################################
# 
# ContingencyElement.py
# Python implementation of the Class ContingencyElement
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:55 PM
# 
#######################################################
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class ContingencyElement(IdentifiedObject):
    """An element of a system event to be studied by contingency analysis,
    representing a change in status of a single piece of equipment.
    """
    pass
