#######################################################
# 
# LimitDependency.py
# Python implementation of the Class LimitDependency
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:59 PM
# Original author: akamath
# 
#######################################################
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class LimitDependency(IdentifiedObject):
    """A limit calculation model used to compute an operational limit based on
    external input such as temperature. These are intended to be shared among
    operational limits with the same calculation form that apply to a piece of
    equipment..
    """
    pass
