# Converted by an OPENAI API call using model: gpt-3.5-turbo-1106 on Thu Dec 28 19:52:13 2023
from enum import Enum

class OASISErrDescription(Enum):
    NO_DATA_RETURNED = 0
    INVALID_DATE_FORMAT = 1
    TIMED_OUT_WAITING_FOR_QUERY_RESPONSE = 2
    DATA_CAN_BE_REQUESTED_FOR_PERIOD_OF_31_DAYS_ONLY = 3
    REPORT_NAME_DOES_NOT_EXIT = 4
    VALIDATION_EXCEPTION_DURING_TRANSFORMATION_OF_XML = 5
    REQUIRED_FILE_DOES_NOT_EXIST = 6
    OUT_OF_MEMORY_EXCEPTION = 7
    EXCEPTIONS_IN_READING_AND_WRITING_OF_XML_FILES = 8
    SYSTEM_ERROR = 9
