#######################################################
# 
# TopologicalIsland.py
# Python implementation of the Class TopologicalIsland
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:28:50 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Topology.TopologicalNode import TopologicalNode
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject


class TopologicalIsland(IdentifiedObject):
    """An electrically connected subset of the network. Topological islands can change
    as the current network state changes: e.g. due to
      - disconnect switches or breakers change state in a SCADA/EMS
      - manual creation, change or deletion of topological nodes in a planning tool.
    """

    def __init__(self):
        super().__init__()
        # The angle reference for the island.   Normally there is one TopologicalNode
        # that is selected as the angle reference for each island.   Other reference
        # schemes exist, so the association is typically optional.
        self.angle_ref_topological_node = TopologicalNode()
        self.topological_nodes = TopologicalNode()   # A topological node belongs to a topological island.
