#######################################################
# 
# DuctBank.py
# Python implementation of the Class DuctBank
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:21 PM
# 
#######################################################
from java.IEC61968.Assets.AssetContainer import AssetContainer

class DuctBank(AssetContainer):
    """A duct contains individual wires in the layout as specified with associated
    wire spacing instances; number of them gives the number of conductors in this
    duct.
    """
    pass
