#######################################################
# 
# AnalogValue.py
# Python implementation of the Class AnalogValue
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 7:42:36 PM
# 
#######################################################

from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Meas.MeasurementValue import MeasurementValue
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Meas.AnalogControl import AnalogControl

class AnalogValue(MeasurementValue):
    """AnalogValue represents an analog MeasurementValue.
    """
    # The Control variable associated with the MeasurementValue.
    def __init__(self):
        super().__init__()
        self.analog_control: AnalogControl  = AnalogControl()
