#######################################################
# 
# Control.py
# Python implementation of the Class Control
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 7:23:14 PM
# 
#######################################################
# from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.String import String
# from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Meas.IOPoint import IOPoint

class Control(IOPoint):
    """Control is used for supervisory/device control. It represents control outputs
    that are used to change the state in a process, e.g. close or open breaker, a
    set point value or a raise lower command.
    """
    def __init__(self):
        super().__init__()
        self.control_type = ""
        self.operation_in_progress = False
        self.timestamp = DateTime ()
        self.unit_multiplier = UnitMultiplier.none
        self.unit_symbol = UnitSymbol.count