#######################################################
# 
# Measurement.py
# Python implementation of the Class Measurement
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 6:59:21 PM
# 
#######################################################
# from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.String import String
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.PhaseCode import PhaseCode
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UncefactUnitCode import UncefactUnitCode
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.ACDCTerminal import ACDCTerminal
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.ProtectiveActionAdjustment import ProtectiveActionAdjustment
from CIM_STD_PYTHON.TC57CIM.IEC61968.AssetMeas.CalculationMethodHierarchy import CalculationMethodHierarchy

class Measurement(IdentifiedObject):
    """A Measurement represents any measured, calculated or non-measured non-
    calculated quantity. Any piece of equipment may contain Measurements, e.g. a
    substation may have temperature measurements and door open indications, a
    transformer may have oil temperature and tank pressure measurements, a bay may
    contain a number of power flow measurements and a Breaker may contain a switch
    status measurement.
      The PSR - Measurement association is intended to capture this use of
    Measurement and is included in the naming hierarchy based on EquipmentContainer.
    The naming hierarchy typically has Measurements as leafs, e.g. Substation-
    VoltageLevel-Bay-Switch-Measurement.
      Some Measurements represent quantities related to a particular sensor
    location in the network, e.g. a voltage transformer (PT) at a busbar or a
    current transformer (CT) at the bar between a breaker and an isolator. The
    sensing position is not captured in the PSR - Measurement association. Instead
    it is captured by the Measurement - Terminal association that is used to define
    the sensing location in the network topology. The location is defined by the
    connection of the Terminal to ConductingEquipment.
      If both a Terminal and PSR are associated, and the PSR is of type
    ConductingEquipment, the associated Terminal should belong to that
    ConductingEquipment instance.
      When the sensor location is needed both Measurement-PSR and Measurement-
    Terminal are used. The Measurement-Terminal association is never used alone.
    """
    # One or more measurements may be associated with a terminal in the network.
    Terminal= ACDCTerminal()

    ProtectiveActionAdjustment= ProtectiveActionAdjustment()

    # Calculation method hierarchy which applies to this analog.
    CalculationMethodHierarchy= CalculationMethodHierarchy()
