#######################################################
# 
# MeasurementValueSource.py
# Python implementation of the Class MeasurementValueSource
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 7:14:51 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Meas.MeasurementValue import MeasurementValue
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class MeasurementValueSource(IdentifiedObject):
    """MeasurementValueSource describes the alternative sources updating a
    MeasurementValue. User conventions for how to use the MeasurementValueSource
    attributes are described in the introduction to IEC 61970-301.
    """

    def __init__(self):
        # The MeasurementValues updated by the source.
        super().__init__()
        self.measurement_values = [MeasurementValue()]