#######################################################
# 
# ValueAliasSet.py
# Python implementation of the Class ValueAliasSet
# Generated by Enterprise Architect
# Created on:      18-Dec-2023 6:30:11 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Meas.ValueToAlias import ValueToAlias
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Meas.Discrete import Discrete
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class ValueAliasSet(IdentifiedObject):
    """
    Describes the translation of a set of values into a name and is intendend to
    facilitate cusom translations. Each ValueAliasSet has a name, description etc.
    A specific Measurement may represent a discrete state like Open, Closed,
    Intermediate etc. This requires a translation from the MeasurementValue.value
    number to a string, e.g.
        0->"Invalid", 1->"Open", 2->"Closed", 3->"Intermediate".
    Each ValueToAlias member in ValueAliasSet.Value describe a
    mapping for one particular value to a name.
    """

    def __init__(self):
        super().__init__()
        self.values = ValueToAlias()    # The ValueToAlias mappings included in the set.
        self.discretes = Discrete()    # The Measurements using the set for translation.