#######################################################
# 
# RemoteUnitType.py
# Python implementation of the Class RemoteUnitType
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:03 PM
# 
#######################################################


class RemoteUnitType:
    """Type of remote unit.
    """
    pass
