#######################################################
# 
# RemoteSource.py
# Python implementation of the Class RemoteSource
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:03 PM
# 
#######################################################
from IEC61970.Base.Domain.Float import Float
from IEC61970.Base.Domain.Seconds import Seconds
from IEC61970.Base.SCADA.RemotePoint import RemotePoint

class RemoteSource(RemotePoint):
    """Remote sources are state variables that are telemetered or calculated within
    the remote unit.
    """
    pass
