#######################################################
# 
# RemotePoint.py
# Python implementation of the Class RemotePoint
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:03 PM
# 
#######################################################
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class RemotePoint(IdentifiedObject):
    """For a RTU remote points correspond to telemetered values or control outputs.
    Other units (e.g. control centers) usually also contain calculated values.
    """
    pass
