#######################################################
# 
# RemoteControl.py
# Python implementation of the Class RemoteControl
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:03 PM
# 
#######################################################
from IEC61970.Base.Domain.Float import Float
from IEC61970.Base.Domain.Boolean import Boolean
from IEC61970.Base.SCADA.RemotePoint import RemotePoint
from IEC61970.Base.Meas.Control import Control

class RemoteControl(RemotePoint):
    """Remote controls are ouputs that are sent by the remote unit to actuators in the
    process.
    """
    # The Control for the RemoteControl point.
    Control= Control()
