#######################################################
# 
# Source.py
# Python implementation of the Class Source
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:03 PM
# 
#######################################################


class Source:
    """Source gives information related to the origin of a value.
    """
    pass
