#######################################################
# 
# Specification.py
# Python implementation of the Class Specification
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:24 PM
# 
#######################################################
from java.IEC61968.InfIEC61968.InfAssets import AssetPropertyCurve
from java.IEC61968.Assets import Medium
from java.IEC61968.Common import Document

class Specification(Document):
    """Specification can be used for various purposes relative to an asset, a logical
    device (PowerSystemResource), location, etc. Examples include documents
    supplied by manufacturers such as asset installation instructions, asset
    maintenance instructions, etc.
    """
    AssetPropertyCurves= AssetPropertyCurve()

    Mediums= Medium()
