#######################################################
# 
# AnalogToDigitalLogicKind.py
# Python implementation of the Class AnalogToDigitalLogicKind
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 6:47:48 PM
# Original author: sveinols
# 
#######################################################


class AnalogToDigitalLogicKind:
    """Categories of analog to digital (or logical result) comparison.
    """
    def __init__(self):
        pass
