#######################################################
# 
# CalculationKind.py
# Python implementation of the Class CalculationKind
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 6:48:20 PM
# Original author: sveinols
# 
#######################################################


class CalculationKind:
    """Categorisation of calculation operation that can be done to Measurement.
    """
    def __init__(self):
        pass
