#######################################################
# 
# Gate.py
# Python implementation of the Class Gate
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 3:50:45 PM
# Original author: sveinols
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.GateLogicKind import GateLogicKind
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.RemedialActionScheme import RemedialActionScheme
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.PinGate import PinGate
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.GateInputPin import GateInputPin

class Gate(IdentifiedObject):
    """Logical gate than support logical operation based on the input.
    """

    def __init__(self):
        super().__init__()
        self.remedial_action_scheme = RemedialActionScheme()
        self.pin_gate = PinGate()
        self.gate_input_pin = GateInputPin()
