#######################################################
# 
# GateLogicKind.py
# Python implementation of the Class GateLogicKind
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 3:54:04 PM
# Original author: sveinols
# 
#######################################################


class GateLogicKind:
    """Define the different logical operations.
    """
    def __init__(self):
        pass
