#######################################################
# 
# PinBranchGroupKind.py
# Python implementation of the Class PinBranchGroupKind
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 6:49:07 PM
# Original author: sveinols
# 
#######################################################


class PinBranchGroupKind:
    """Categorisation of type of compare done on a branch group.
    """
    def __init__(self):
        pass
