#######################################################
# 
# PinEquipmentKind.py
# Python implementation of the Class PinEquipmentKind
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 6:50:17 PM
# Original author: sveinols
# 
#######################################################


class PinEquipmentKind:
    """Categorisation of type of compare done on Equipment.
    """
    def __init__(self):
        pass
