#######################################################
# 
# PinEquipment.py
# Python implementation of the Class PinEquipment
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 6:37:49 PM
# Original author: sveinols
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.PinEquipmentKind import PinEquipmentKind
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.Equipment import Equipment
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.GateInputPin import GateInputPin

class PinEquipment(GateInputPin):
    """Value associated with Equipment is used as compare.
    """

    def __init__(self):
        super().__init__()
        self.equipment = Equipment()
