#######################################################
# 
# PinGate.py
# Python implementation of the Class PinGate
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 3:53:06 PM
# Original author: sveinols
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.GateInputPin import GateInputPin

class PinGate(GateInputPin):
    """An output from one gate represent an input to another gate.
    """
    def __init__(self):
        super().__init__()
