#######################################################
# 
# PinTerminalKind.py
# Python implementation of the Class PinTerminalKind
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 6:50:41 PM
# Original author: sveinols
# 
#######################################################


class PinTerminalKind:
    """Categorisation of type of compare done on Terminal.
    """
    def __init__(self):
        pass
