#######################################################
# 
# ProtectiveAction.py
# Python implementation of the Class ProtectiveAction
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 3:50:17 PM
# Original author: sveinols
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.Gate import Gate


class ProtectiveAction(IdentifiedObject):
    """A protective action for supporting the integrity of the power system.
    """
    def __init__(self):
        super().__init__()
        self.gate_com_condition= Gate()
        self.gate_enabled_condition= Gate()