#######################################################
# 
# ProtectiveActionAdjustment.py
# Python implementation of the Class ProtectiveActionAdjustment
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 3:49:49 PM
# Original author: sveinols
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.PerCent import PerCent
# from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Float import Float
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.ProtectiveActionAdjustmentKind import ProtectiveActionAdjustmentKind
# from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.DC.DCConductingEquipment import DCConductingEquipment
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.ProtectiveAction import ProtectiveAction

class ProtectiveActionAdjustment(ProtectiveAction):
    """
    Protective actions on non-switching equipment. The operating condition is
    adjusted.
    """
    def __init__(self):
        super().__init__()
        self.dc_conducting_equipment = DCConductingEquipment()