#######################################################
# 
# ProtectiveActionAdjustment.py
# Python implementation of the Class ProtectiveActionAdjustment
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 3:49:49 PM
# Original author: sveinols
# 
#######################################################
from IEC61970.Base.DC.DCConductingEquipment import DCConductingEquipment
from IEC61970.InfIEC61970.InfSIPS.ProtectiveAction import ProtectiveAction

class ProtectiveActionAdjustment(ProtectiveAction):
    """
    Protective actions on non-switching equipment. The operating condition is
    adjusted.
    """
    def __init__(self):
        super().__init__()
        self.dc_conducting_equipment = DCConductingEquipment()