#######################################################
# 
# ProtectiveActionAdjustmentKind.py
# Python implementation of the Class ProtectiveActionAdjustmentKind
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 3:55:41 PM
# Original author: sveinols
# 
#######################################################


class ProtectiveActionAdjustmentKind:
    """
    Categorisation of different protective action adjustments that can be performed
    on equipment.
    """

    def __init__(self):
        pass

