#######################################################
# 
# ProtectiveActionRegulation.py
# Python implementation of the Class ProtectiveActionRegulation
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 6:46:29 PM
# Original author: sveinols
# 
#######################################################
# from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
# from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Float import Float
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Wires.RegulatingControl import RegulatingControl
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.ProtectiveAction import ProtectiveAction


class ProtectiveActionRegulation(ProtectiveAction):
    """Protective action to change regulation to Equipment.
    """

    def __init__(self):
        super().__init__()
        self.regulating_control = RegulatingControl()
