#######################################################
# 
# RemedialActionSchemeKind.py
# Python implementation of the Class RemedialActionSchemeKind
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 3:57:19 PM
# Original author: sveinols
# 
#######################################################


class RemedialActionSchemeKind:
    """Classification of Remedial Action Scheme.
    """
    def __init__(self):
        pass
