#######################################################
# 
# Stage.py
# Python implementation of the Class Stage
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 3:56:50 PM
# Original author: sveinols
# 
#######################################################
# from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Integer import Integer
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.StageTrigger import StageTrigger

class Stage(IdentifiedObject):
    """
    Stage of a remedial action scheme.
    """

    def __init__(self):
        super().__init__()
        self.stage_trigger = StageTrigger()