#######################################################
# 
# TriggerCondition.py
# Python implementation of the Class TriggerCondition
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 6:47:11 PM
# Original author: sveinols
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.RemedialActionScheme import RemedialActionScheme
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.Gate import Gate

class TriggerCondition(IdentifiedObject):
    """
    A conditions that can trigger remedial actions.
    """

    def __init__(self):
        super().__init__()
        self.remedial_action_scheme = RemedialActionScheme()
        self.gate_trigger = Gate()