#######################################################
# 
# AngleDegrees.py
# Python implementation of the Class AngleDegrees
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:54 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Domain.Float import Float

class AngleDegrees:
    """Measurement of angle in degrees.
    """
    multiplier = none
    unit = deg