#######################################################
# 
# ApparentPower.py
# Python implementation of the Class ApparentPower
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:54 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UncefactUnitCode import UncefactUnitCode
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Domain.Float import Float

class ApparentPower:
    """Product of the RMS value of the voltage and the RMS value of the current.
    """
    unit = VA