#######################################################
# 
# InductancePerLength.py
# Python implementation of the Class InductancePerLength
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:59 PM
# Original author: T. Kostic
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Domain.Float import Float

class InductancePerLength:
    """Inductance per unit of length.
    """
    multiplier = none
    unit = HPerm