#######################################################
# 
# KiloActivePower.py
# Python implementation of the Class KiloActivePower
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:59 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Domain.Float import Float

class KiloActivePower:
    """Active power in kilowatts.
    """
    multiplier = k
    unit = W