#######################################################
# 
# Money.py
# Python implementation of the Class Money
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:00 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.Currency import Currency
from IEC61970.Base.Domain.Decimal import Decimal

class Money:
    """Amount of money.
    """
    pass
