#######################################################
# 
# MonthDay.py
# Python implementation of the Class MonthDay
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:00 PM
# Original author: selaost1
# 
#######################################################


class MonthDay:
    """MonthDay format as "--mm-dd", which conforms with XSD data type gMonthDay.
    """
    pass
