#######################################################
# 
# PerCent.py
# Python implementation of the Class PerCent
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:01 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Domain.Float import Float

class PerCent:
    """Percentage on a defined base.   For example, specify as 100 to indicate at the
    defined base.
    """
    multiplier = none
    unit = none