#######################################################
# 
# Reactance.py
# Python implementation of the Class Reactance
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:02 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Domain.Float import Float

class Reactance:
    """Reactance (imaginary part of impedance), at rated frequency.
    """
    unit = ohm