#######################################################
# 
# ReactivePower.py
# Python implementation of the Class ReactivePower
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:03 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Domain.Float import Float

class ReactivePower:
    """Product of RMS value of the voltage and the RMS value of the quadrature
    component of the current.
    """
    unit = VAr