#######################################################
# 
# RealEnergy.py
# Python implementation of the Class RealEnergy
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:03 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UncefactUnitCode import UncefactUnitCode
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Domain.Float import Float

class RealEnergy:
    """Real electrical energy.
    """
    unit = Wh