#######################################################
# 
# Speed.py
# Python implementation of the Class Speed
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:03 PM
# Original author: T. Kostic
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Domain.Float import Float

class Speed:
    """Distance per unit of time.
    """
    multiplier = none
    unit = mPers