#######################################################
# 
# StringQuantity.py
# Python implementation of the Class StringQuantity
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:03 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Domain.String import String

class StringQuantity:
    """Quantity with string value (when it is not important whether it is an integral
    or a floating point number) and associated unit information.
    """
    pass
