#######################################################
# 
# Susceptance.py
# Python implementation of the Class Susceptance
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:03 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Domain.Float import Float

class Susceptance:
    """Imaginary part of admittance.
    """
    unit = S