#######################################################
# 
# Temperature.py
# Python implementation of the Class Temperature
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:04 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Domain.Float import Float

class Temperature:
    """Value of temperature in degrees Celsius.
    """
    multiplier = none
    unit = degC