#######################################################
# 
# TimeInterval.py
# Python implementation of the Class TimeInterval
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:04 PM
# Original author: T. Kostic
# 
#######################################################
from IEC61970.Base.Domain.Time import Time

class TimeInterval:
    """Interval between two times.
    """
    pass
