#######################################################
# 
# VoltagePerReactivePower.py
# Python implementation of the Class VoltagePerReactivePower
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:05 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Domain.Float import Float

class VoltagePerReactivePower:
    """Voltage variation with reactive power.
    """
    unit = VPerVAr