#######################################################
# 
# EndDeviceFunction.py
# Python implementation of the Class EndDeviceFunction
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:21 PM
# 
#######################################################
from java.IEC61968.Assets import AssetFunction

class EndDeviceFunction(AssetFunction):
    """Function performed by an end device such as a meter, communication equipment,
    controllers, etc.
    """
    pass
