#######################################################
# 
# Connector.py
# Python implementation of the Class Connector
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:55 PM
# 
#######################################################
from IEC61970.Base.Core.ConductingEquipment import ConductingEquipment

class Connector(ConductingEquipment):
    """A conductor, or group of conductors, with negligible impedance, that serve to
    connect other conducting equipment within a single substation and are modelled
    with a single logical terminal.
    """
    pass
