#######################################################
# 
# DesignLocation.py
# Python implementation of the Class DesignLocation
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:20 PM
# 
#######################################################
from java.IEC61968.InfIEC61968 import MiscCostItem
from java.IEC61968.InfIEC61968 import DesignLocationCU
from java.IEC61968.InfIEC61968 import Design
from java.IEC61968.InfIEC61968 import WorkIdentifiedObject
from java.IEC61968.InfIEC61968 import ConditionFactor
from IEC61968 import WorkLocation

class DesignLocation(WorkIdentifiedObject):
    """A logical part of the design (e.g., pole and all equipment on a pole). This
    includes points and spans.
    """
    MiscCostItems= MiscCostItem()

    DesignLocationCUs= DesignLocationCU()

    Designs= Design()

    ConditionFactors= ConditionFactor()

    WorkLocations= WorkLocation()
