#######################################################
# 
# OneCallRequest.py
# Python implementation of the Class OneCallRequest
# Generated by Enterprise Architect
# Created on:      02-Jan-2024 9:58:07 PM
# 
#######################################################
from IEC61970.Base.Domain.Boolean import Boolean
from IEC61970.Base.Domain.String import String
from IEC61968.InfIEC61968.InfWork.WorkDocument import WorkDocument

class OneCallRequest(WorkDocument):
    """A request for other utilities to mark their underground facilities prior to
    commencement of construction and/or maintenance.
    """
    pass
