#######################################################
# 
# Project.py
# Python implementation of the Class Project
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:24 PM
# 
#######################################################
from IEC61968 import WorkDocument

class Project(WorkDocument):
    """A collection of related work. For construction projects and maintenance
    projects, multiple phases may be performed.
    """
    SubProjects= Project()
