#######################################################
# 
# Project.py
# Python implementation of the Class Project
# Generated by Enterprise Architect
# Created on:      02-Jan-2024 9:58:07 PM
# 
#######################################################
from IEC61970.Base.Domain.Money import Money
from IEC61968.InfIEC61968.InfWork.WorkDocument import WorkDocument

class Project(WorkDocument):
    """A collection of related work. For construction projects and maintenance
    projects, multiple phases may be performed.
    """
    SubProjects= Project()
