#######################################################
# 
# WorkDocument.py
# Python implementation of the Class WorkDocument
# Generated by Enterprise Architect
# Created on:      02-Jan-2024 9:58:07 PM
# Original author: T. Kostic
# 
#######################################################
from IEC61968.Common.Document import Document

class WorkDocument(Document):
    """Shadow class for Document, to isolate subclassing from this package. If any
    subclass gets normative and needs inheritance, it will inherit directly from
    Document.
    """
    pass
