#######################################################
# 
# WorkDocument.py
# Python implementation of the Class WorkDocument
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:26 PM
# Original author: T. Kostic
# 
#######################################################
from java.IEC61968.Common import Document

class WorkDocument(Document):
    """Shadow class for Document, to isolate subclassing from this package. If any
    subclass gets normative and needs inheritance, it will inherit directly from
    Document.
    """
    pass
