#######################################################
# 
# DesignLocation.py
# Python implementation of the Class DesignLocation
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 6:19:21 PM
# 
#######################################################


from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Length import Length
from CIM_STD_PYTHON.TC57CIM.IEC61968.Common.Status import Status
from CIM_STD_PYTHON.TC57CIM.IEC61968.InfIEC61968.InfWork.MiscCostItem import MiscCostItem
from CIM_STD_PYTHON.TC57CIM.IEC61968.InfIEC61968.InfWork.DesignLocationCU import DesignLocationCU
from CIM_STD_PYTHON.TC57CIM.IEC61968.InfIEC61968.InfWork.Design import Design
from CIM_STD_PYTHON.TC57CIM.IEC61968.InfIEC61968.InfWork.WorkIdentifiedObject import WorkIdentifiedObject
from CIM_STD_PYTHON.TC57CIM.IEC61968.InfIEC61968.InfWork.ConditionFactor import ConditionFactor
from CIM_STD_PYTHON.TC57CIM.IEC61968.Work.WorkLocation import WorkLocation

class DesignLocation(WorkIdentifiedObject):
    """A logical part of the design (e.g., pole and all equipment on a pole). This
    includes points and spans.
    """

    def __init__(self):
        self.misc_cost_items = MiscCostItem()
        self.design_location_cus = DesignLocationCU()
        self.designs = Design()
        self.condition_factors = ConditionFactor()
        self.work_locations = WorkLocation()