#######################################################
# 
# WorkDocument.py
# Python implementation of the Class WorkDocument
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 8:46:58 PM
# Original author: T. Kostic
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61968.Common.Document import Document


class WorkDocument(Document):
    """Shadow class for Document, to isolate subclassing from this package. If any
    subclass gets normative and needs inheritance, it will inherit directly from
    Document.
    """

    def __init__(self):
        super().__init__()
