package IEC62325.InfIEC62325.InfDomain;


/**
 * MIN_CONSTRAINT
 * MAX_CONSTRAINT
 * FIXED_CONSTRAINT
 * @created 03-Jan-2024 1:48:21 PM
 */
public enum ADSInstructionTypeOOS {
	MIN_CONSTRAINT,
	MAX_CONSTRAINT,
	FIXED_CONSTRAINT
}