#######################################################
# 
# AssetContainer.py
# Python implementation of the Class AssetContainer
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 11:25:06 AM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61968.Assets.Asset import Asset
from CIM_STD_PYTHON.TC57CIM.IEC61968.Assets.Seal import Seal


class AssetContainer(Asset):
    """Asset that is aggregation of other assets such as conductors, transformers,
    switchgear, land, fences, buildings, equipment, vehicles, etc.
    """
    # All seals applied to this asset container.
    def __init__(self):
        super().__init__()
        self.seal = Seal()
