# Converted by an OPENAI API call using model: gpt-3.5-turbo-1106
# assets.py

from enum import Enum

class BreakerFailureReasonKind(Enum):
    BLAST_VALVE_FAILURE = 1
    BUSHING_FAILURE = 2
    CLOSE_COIL_OPEN_SHORTED_FAILED = 3
    CONTAMINATED_AIR = 4
    CONTAMINATED_ARC_CHUTES = 5
    CONTAMINATED_GAS = 6
    CONTAMINATED_GAS_AIR = 7
    CONTROL_CIRCUIT_FAILURE = 8
    DEGRADED_LUBRICATION = 9
    EXTERNAL_OR_INTERNAL_CONTAMINATION = 10
    HIGH_PRESSURE_AIR_PLANT = 11
    HIGH_RESISTANCE_LOAD_PATH = 12
    HIGH_RESISTANCE_PATH = 13
    INTERRUPTER_CONTACT_FAILURE = 14
    INTERRUPTER_FAILURE = 15
    LINKAGE_FAILURE = 16
    LOSS_OF_OIL = 17
    LOSS_OF_VACUUM = 18
    LOW_GAS_PRESSURE = 19
    MECHANISM_FAILURE = 20
    MECHANISM_OR_LINKAGE_FAILURE = 21
    OIL_RELATED_FAILURE = 22
    POOR_OIL_QUALITY = 23
    RACKING_MECHANISM_FAILURE = 24
    RESISTOR_FAILURE = 25
    RESISTOR_GRADING_CAPACITOR_FAILURE = 26
    SF6_BLAST_VALVE_FAILURE = 27
    SF6_PUFFER_FAILURE = 28
    SOLID_DIELECTRIC_FAILURE = 29
    STORED_ENERGY_FAILURE = 30
    TRIP_COIL_OPEN_SHORTED_FAILED = 31
