# Converted by an OPENAI API call using model: gpt-3.5-turbo-1106
# assets.py
from enum import Enum


class BreakerApplicationKind(Enum):
    CAPACITOR_OR_REACTOR_BANK_BREAKER = 1   #  "CAPACITORORREACTORBANKBREAKER"
    BUS_BREAKER = 2   #  "BUSBREAKER"
    BUS_TIE_BREAKER = 3   #  "BUSTIEBREAKER"
    FEEDER_BREAKER = 4   #  "FEEDERBREAKER"
    STEP_UP_TRANSFORMER_BREAKER_HYDRO = 5   #  "STEPUPTRANSFORMERBREAKERHYDRO"
    STEP_UP_TRANSFORMER_BREAKER_FOSSIL = 6   #  "STEPUPTRANSFORMERBREAKERFOSSIL"
    STEP_UP_TRANSFORMER_BREAKER_NUCLEAR = 7   #  "STEPUPTRANSFORMERBREAKERNUCLEAR"
    STEP_UP_TRANSFORMER_BREAKER_PUMPED_STORAGE = 8   #  "STEPUPTRANSFORMERBREAKERPUMPEDSTORAGE"
    SUBSTATION_TRANSFORMER_BREAKER = 9   #  "SUBSTATIONTRANSFORMERBREAKER"
    TRANSMISSION_FLOW_GATE_LINE_BREAKER = 10   #  "TRANSMISSIONFLOWGATELINEBREAKER"
    TRANSMISSION_LINE_BREAKER = 11   #  "TRANSMISSIONLINEBREAKER"
    TRANSMISSION_TIE_LINE_BREAKER = 12   #  "TRANSMISSIONTIELINEBREAKER"
    SPARE = 12   #  "SPARE"
    OTHER = 14   #  "OTHER"
