# Converted by an OPENAI API call using model: gpt-3.5-turbo-1106
# iso_standard_kind.py

from enum import Enum

class ISOStandardKind(Enum):
    
    DETERMINATION_OF_FLASH_AND_FIRE_POINTS = 2592
    DETERMINATION_OF_FLASH_POINT = 2719
    DETERMINATION_OF_POUR_POINT = 3016
    TRANSPARENT_AND_OPAQUE_LIQUIDS = 3104
    LABORATORY_DETERMINATION_OF_DENSITY = 3675
    DETERMINATION_OF_TENSILE_STRENGTH = 1924
    DETERMINATION_OF_TENSILE_PROPERTIES_CONSTANT_RATE_OF_LOADING_METHOD = 1924
    DETERMINATION_OF_TENSILE_PROPERTIES_CONSTANT_RATE_OF_ELONGATION_METHOD_20_MM_MIN = 1924
    DETERMINATION_OF_TENSILE_PROPERTIES_CONSTANT_RATE_OF_ELONGATION_METHOD_100_MM_MIN = 1924
