#######################################################
# 
# BasePower.py
# Python implementation of the Class BasePower
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:54 PM
# 
#######################################################
from IEC61970.Base.Domain.ApparentPower import ApparentPower
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class BasePower(IdentifiedObject):
    """The BasePower class defines the base power used in the per unit calculations.
    """
    pass
