#######################################################
# 
# Bay.py
# Python implementation of the Class Bay
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:54 PM
# 
#######################################################
from IEC61970.Base.Domain.Boolean import Boolean
from IEC61970.Base.Core.BreakerConfiguration import BreakerConfiguration
from IEC61970.Base.Core.BusbarConfiguration import BusbarConfiguration
from IEC61970.Base.Core.EquipmentContainer import EquipmentContainer

class Bay(EquipmentContainer):
    """A collection of power system resources (within a given substation) including
    conducting equipment, protection relays, measurements, and telemetry.  A bay
    typically represents a physical grouping related to modularization of equipment.
    """
    pass
