#######################################################
# 
# BreakerConfiguration.py
# Python implementation of the Class BreakerConfiguration
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:54 PM
# 
#######################################################


class BreakerConfiguration:
    """Switching arrangement for bay.
    """
    pass
