#######################################################
# 
# ConnectivityNodeContainer.py
# Python implementation of the Class ConnectivityNodeContainer
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:55 PM
# 
#######################################################
from IEC61970.Base.Core.PowerSystemResource import PowerSystemResource

class ConnectivityNodeContainer(PowerSystemResource):
    """A base class for all objects that may contain connectivity nodes or topological
    nodes.
    """
    pass
