#######################################################
# 
# ConnectivityNode.py
# Python implementation of the Class ConnectivityNode
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:55 PM
# 
#######################################################
from IEC61970.Base.Core.ConnectivityNodeContainer import ConnectivityNodeContainer
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class ConnectivityNode(IdentifiedObject):
    """Connectivity nodes are points where terminals of AC conducting equipment are
    connected together with zero impedance.
    """
    # Container of this connectivity node.
    ConnectivityNodeContainer= ConnectivityNodeContainer()
