#######################################################
# 
# Curve.py
# Python implementation of the Class Curve
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:55 PM
# 
#######################################################
from IEC61970.Base.Core.CurveStyle import CurveStyle
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from IEC61970.Base.Core.CurveData import CurveData

class Curve(IdentifiedObject):
    """A multi-purpose curve or functional relationship between an independent
    variable (X-axis) and dependent (Y-axis) variables.
    """
    # The point data values that define this curve.
    CurveDatas= CurveData()
