#######################################################
# 
# CurveData.py
# Python implementation of the Class CurveData
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:55 PM
# 
#######################################################
from IEC61970.Base.Domain.Float import Float

class CurveData:
    """Multi-purpose data points for defining a curve.  The use of this generic class
    is discouraged if a more specific class  can be used to specify the x and y
    axis values along with their specific data types.
    """
    pass
