#######################################################
# 
# Equipment.py
# Python implementation of the Class Equipment
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:56 PM
# 
#######################################################
from IEC61970.Base.Domain.Boolean import Boolean
from IEC61970.Base.Core.PowerSystemResource import PowerSystemResource
from IEC61970.InfIEC61970.InfOperationalLimits.WeatherStation import WeatherStation
from IEC61970.InfIEC61970.InfOperationalLimits.LimitDependency import LimitDependency

class Equipment(PowerSystemResource):
    """The parts of a power system that are physical devices, electronic or mechanical.
    """
    WeatherStation= WeatherStation()

    # Limit dependencymodels organized under this equipment as a means for organizing
    # the model in a tree view.
    LimitDependencyModel= LimitDependency()
