#######################################################
# 
# PowerSystemResource.py
# Python implementation of the Class PowerSystemResource
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:02 PM
# 
#######################################################
from IEC61970.Base.Meas.Control import Control
from IEC61970.Base.Meas.Measurement import Measurement
from IEC61970.Base.Core.PSRType import PSRType
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from java.IEC61968.Common.ConfigurationEvent import ConfigurationEvent

class PowerSystemResource(IdentifiedObject):
    """A power system resource can be an item of equipment such as a switch, an
    equipment container containing many individual items of equipment such as a
    substation, or an organisational entity such as sub-control area. Power system
    resources can have measurements associated.
    """
    # The controller outputs used to actually govern a regulating device, e.g. the
    # magnetization of a synchronous machine or capacitor bank breaker actuator.
    Controls= Control()

    # The measurements associated with this power system resource.
    Measurements= Measurement()

    # Custom classification for this power system resource.
    PSRType= PSRType()

    ConfigurationEvent= ConfigurationEvent()
