#######################################################
# 
# PSRType.py
# Python implementation of the Class PSRType
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:02 PM
# 
#######################################################
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class PSRType(IdentifiedObject):
    """Classifying instances of the same class, e.g. overhead and underground
    ACLineSegments. This classification mechanism is intended to provide
    flexibility outside the scope of this standard, i.e. provide customisation that
    is non standard.
    """
    pass
