#######################################################
# 
# RegularTimePoint.py
# Python implementation of the Class RegularTimePoint
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:03 PM
# 
#######################################################
from IEC61970.Base.Domain.Integer import Integer
from IEC61970.Base.Domain.Float import Float

class RegularTimePoint:
    """Time point for a schedule where the time between the consecutive points is
    constant.
    """
    pass
