#######################################################
# 
# RegularIntervalSchedule.py
# Python implementation of the Class RegularIntervalSchedule
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:03 PM
# 
#######################################################
from IEC61970.Base.Domain.DateTime import DateTime
from IEC61970.Base.Domain.Seconds import Seconds
from IEC61970.Base.Core.RegularTimePoint import RegularTimePoint
from IEC61970.Base.Core.BasicIntervalSchedule import BasicIntervalSchedule

class RegularIntervalSchedule(BasicIntervalSchedule):
    """The schedule has time points where the time between them is constant.
    """
    # The regular interval time point data values that define this schedule.
    TimePoints= RegularTimePoint()
