#######################################################
# 
# TopologicalNode.py
# Python implementation of the Class TopologicalNode
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:04 PM
# 
#######################################################
from IEC61970.Base.Domain.ActivePower import ActivePower
from IEC61970.Base.Domain.ReactivePower import ReactivePower
from IEC61970.Base.Core.ReportingGroup import ReportingGroup
from IEC61970.Base.Core.ConnectivityNodeContainer import ConnectivityNodeContainer
from IEC61970.Base.Core.BaseVoltage import BaseVoltage
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from IEC61970.Base.Core.ConnectivityNode import ConnectivityNode
from IEC61970.Base.Core.Terminal import Terminal

class TopologicalNode(IdentifiedObject):
    """For a detailed substation model a topological node is a set of connectivity
    nodes that, in the current network state, are connected together through any
    type of closed switches, including  jumpers. Topological nodes change as the
    current network state changes (i.e., switches, breakers, etc. change state).
      For a planning model, switch statuses are not used to form topological nodes.
    Instead they are manually created or deleted in a model builder tool.
    Topological nodes maintained this way are also called "busses".
    """
    # The reporting group to which the topological node belongs.
    ReportingGroup= ReportingGroup()

    # The connectivity node container to which the toplogical node belongs.
    ConnectivityNodeContainer= ConnectivityNodeContainer()

    # The base voltage of the topologocial node.
    BaseVoltage= BaseVoltage()

    # The connectivity nodes combine together to form this topological node.  May
    # depend on the current state of switches in the network.
    ConnectivityNodes= ConnectivityNode()

    # The terminals associated with the topological node.   This can be used as an
    # alternative to the connectivity node path to terminal, thus making it
    # unneccesary to model connectivity nodes in some cases.   Note that if
    # connectivity nodes are in the model, this association would probably not be
    # used as an input specification.
    Terminal= Terminal()
