#######################################################
# 
# TopologicalIsland.py
# Python implementation of the Class TopologicalIsland
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:04 PM
# 
#######################################################
from IEC61970.Base.Topology.TopologicalNode import TopologicalNode
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class TopologicalIsland(IdentifiedObject):
    """An electrically connected subset of the network. Topological islands can change
    as the current network state changes: e.g. due to
      - disconnect switches or breakers change state in a SCADA/EMS
      - manual creation, change or deletion of topological nodes in a planning tool.
    """
    # The angle reference for the island.   Normally there is one TopologicalNode
    # that is selected as the angle reference for each island.   Other reference
    # schemes exist, so the association is typically optional.
    AngleRefTopologicalNode= TopologicalNode()

    # A topological node belongs to a topological island.
    TopologicalNodes= TopologicalNode()
