# Converted by an OPENAI API call using model: gpt-3.5-turbo-1106
# asset_meas.py

from enum import Enum

class InspectionDiscreteKind(Enum):
    VISIBLE_DAMAGE_OR_LEAKS = 1
    CONTROL_CABINET_HEATER_ON = 2
    BUSHING_OIL_LEVELS_OK = 3
    OIL_TANK_LEVELS_OK = 4
    SPRING_PRESSURE_READING_OK = 5
    GAS_INDICATOR_NORMAL = 6
    HYDRAULIC_OIL_LEVEL_OK = 7
    HYDRAULIC_FLUID_LEVEL_OK = 8
    CHECK_OIL_LEVEL_OK = 9
    OPERATION_COUNT = 10
    MOTOR_OPERATIONS_COUNT = 11
    PUMP_MOTOR_OPERATION_COUNT = 12
    LOW_TO_HIGH_PRESSURE_COUNT = 13
