#######################################################
# 
# RemotePoint.py
# Python implementation of the Class RemotePoint
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 7:18:36 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class RemotePoint(IdentifiedObject):
    """For a RTU remote points correspond to telemetered values or control outputs.
    Other units (e.g. control centers) usually also contain calculated values.
    """
    def __init__(self):
        super().__init__()

