#######################################################
# 
# RemoteSource.py
# Python implementation of the Class RemoteSource
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 7:18:52 PM
# 
#######################################################
# from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Float import Float
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Seconds import Seconds
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.SCADA.RemotePoint import RemotePoint

class RemoteSource(RemotePoint):
    """Remote sources are state variables that are telemetered or calculated within
    the remote unit.
    """
    def __init__(self):
        super().__init__()
        self.deadband = 0.0
        self.scan_interval = Seconds()
        self.sensor_maximum = 1.0
        self.sensor_minimum = 0.0

