#######################################################
# 
# RemoteUnitType.py
# Python implementation of the Class RemoteUnitType
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 7:19:26 PM
# 
#######################################################
from enum import Enum

class RemoteUnitType(Enum):
    """Type of remote unit.
    """
    RTU = 0
    SUBSTATION_CONTROL_SYSTEM = 1
    CONTROL_CENTER = 2
    IED = 3