#######################################################
# 
# EnergyArea.py
# Python implementation of the Class EnergyArea
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 7:45:43 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject


class EnergyArea(IdentifiedObject):
    """Describes an area having energy production or consumption.  Specializations are
    intended to support the load allocation function as typically required in
    energy management systems or planning studies to allocate hypothesized load
    levels to individual load points for power flow analysis.  Often the energy
    area can be linked to both measured and forecast load levels.
    """

    def __init__(self):
        super().__init__()

