#######################################################
# LoadResponseCharacteristic.py
# Python implementation of the Class LoadResponseCharacteristic
# Generated by Enterprise Architect
# Created on:      18-Dec-2023 12:36:20 AM
# Original author: kdd
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject


class LoadResponseCharacteristic(IdentifiedObject):
    """Models the characteristic response of the load demand due to changes in system
    conditions such as voltage and frequency. This is not related to demand
    response.
    
      If LoadResponseCharacteristic.exponentModel is True, the voltage exponents
    are specified and used as to calculate:
    
      Active power component = Pnominal * (Voltage/cim:BaseVoltage.nominalVoltage)
    ** cim:LoadResponseCharacteristic.pVoltageExponent
    
      Reactive power component = Qnominal * (Voltage/cim:BaseVoltage.
    nominalVoltage)** cim:LoadResponseCharacteristic.qVoltageExponent
    
      Where  * means "multiply" and ** is "raised to power of".
    """

    def __init__(self):
        super().__init__()
        self.exponent_model = False  # Indicates the exponential voltage dependency model is to be used. If false, the coefficient model is to be used.
        self.p_constant_current = 0.0  # Portion of active power load modeled as constant current.
        self.p_constant_impedance = 0.0  # Portion of active power load modeled as constant impedance.
        self.p_constant_power = 0.0  # Portion of active power load modeled as constant power.
        self.p_frequency_exponent = 0.0  # Exponent of per unit frequency effecting active power.
        self.p_voltage_exponent = 0.0  # Exponent of per unit voltage effecting real power.
        self.q_constant_current = 0.0  # Portion of reactive power load modeled as constant current.
        self.q_constant_impedance = 0.0  # Portion of reactive power load modeled as constant impedance.
        self.q_constant_power = 0.0  # Portion of reactive power load modeled as constant power.
        self.q_frequency_exponent = 0.0  # Exponent of per unit frequency effecting reactive power.
        self.q_voltage_exponent = 0.0  # Exponent of per unit voltage effecting reactive power.
