package IEC61970.Dynamics.StandardModels.TurbineGovernorDynamics;

import IEC61970.Base.Domain.PU;
import IEC61970.Base.Domain.Float;
import IEC61970.Base.Domain.Seconds;

/**
 * Detailed electro-hydraulic governor for steam unit.
 * @author pcha006
 * @version 1.0
 * @created 25-Dec-2023 8:31:59 PM
 */
public class GovSteamFV4 extends TurbineGovernorDynamics {

	/**
	 * Minimum value of pressure regulator output (Cpsmn).  Typical Value = -1.
	 */
	public PU cpsmn;
	/**
	 * Maximum value of pressure regulator output (Cpsmx).  Typical Value = 1.
	 */
	public PU cpsmx;
	/**
	 * Minimum value of regulator set-point (Crmn).  Typical Value = 0.
	 */
	public PU crmn;
	/**
	 * Maximum value of regulator set-point (Crmx).  Typical Value = 1.2.
	 */
	public PU crmx;
	/**
	 * Derivative gain of pressure regulator (Kdc).  Typical Value = 1.
	 */
	public PU kdc;
	/**
	 * Frequency bias (reciprocal of droop) (Kf1).  Typical Value = 20.
	 */
	public PU kf1;
	/**
	 * Frequency control (reciprocal of droop) (Kf3).  Typical Value = 20.
	 */
	public PU kf3;
	/**
	 * Fraction  of total turbine output generated by HP part (Khp).  Typical Value =
	 * 0.35.
	 */
	public PU khp;
	/**
	 * Integral gain of pressure regulator (Kic).  Typical Value = 0.0033.
	 */
	public PU kic;
	/**
	 * Integral gain of pressure feedback regulator (Kip).  Typical Value = 0.5.
	 */
	public PU kip;
	/**
	 * Integral gain of electro-hydraulic regulator (Kit).  Typical Value = 0.04.
	 */
	public PU kit;
	/**
	 * First gain coefficient of  intercept valves characteristic (Kmp1).  Typical
	 * Value = 0.5.
	 */
	public PU kmp1;
	/**
	 * Second gain coefficient of intercept valves characteristic (Kmp2).  Typical
	 * Value = 3.5.
	 */
	public PU kmp2;
	/**
	 * Proportional gain of pressure regulator (Kpc).  Typical Value = 0.5.
	 */
	public PU kpc;
	/**
	 * Proportional gain of pressure feedback regulator (Kpp).  Typical Value = 1.
	 */
	public PU kpp;
	/**
	 * Proportional gain of electro-hydraulic regulator (Kpt).  Typical Value = 0.3.
	 */
	public PU kpt;
	/**
	 * Maximum variation of fuel flow (Krc).  Typical Value = 0.05.
	 */
	public PU krc;
	/**
	 * Pressure loss due to flow friction in the boiler tubes (Ksh).  Typical Value =
	 * 0.08.
	 */
	public PU ksh;
	/**
	 * Maximum negative power error (Lpi).  Typical Value = -0.15.
	 */
	public PU lpi;
	/**
	 * Maximum positive power error (Lps).  Typical Value = 0.03.
	 */
	public PU lps;
	/**
	 * Lower limit for frequency correction (MN<sub>EF</sub>).  Typical Value = -0.05.
	 */
	public PU mnef;
	/**
	 * Upper limit for frequency correction (MX<sub>EF</sub>).  Typical Value = 0.05.
	 */
	public PU mxef;
	/**
	 * First value of pressure set point static characteristic (Pr1).  Typical Value =
	 * 0.2.
	 */
	public PU pr1;
	/**
	 * Second value of pressure set point static characteristic, corresponding to Ps0
	 * = 1.0 PU (Pr2).  Typical Value = 0.75.
	 */
	public PU pr2;
	/**
	 * Minimum value of pressure set point static characteristic (Psmn).  Typical
	 * Value = 1.
	 */
	public PU psmn;
	/**
	 * Minimum value of integral regulator (Rsmimn).  Typical Value = 0.
	 */
	public PU rsmimn;
	/**
	 * Maximum value of integral regulator (Rsmimx).  Typical Value = 1.1.
	 */
	public PU rsmimx;
	/**
	 * Minimum value of integral regulator (Rvgmn).  Typical Value = 0.
	 */
	public PU rvgmn;
	/**
	 * Maximum value of integral regulator (Rvgmx).  Typical Value = 1.2.
	 */
	public PU rvgmx;
	/**
	 * Minimum valve opening (Srmn).  Typical Value = 0.
	 */
	public PU srmn;
	/**
	 * Maximum valve opening (Srmx).  Typical Value = 1.1.
	 */
	public PU srmx;
	/**
	 * Intercept valves characteristic discontinuity point (Srsmp).  Typical Value = 0.
	 * 43.
	 */
	public PU srsmp;
	/**
	 * Maximum regulator gate closing velocity (Svmn).  Typical Value = -0.0333.
	 */
	public Float svmn;
	/**
	 * Maximum regulator gate opening velocity (Svmx).  Typical Value = 0.0333.
	 */
	public Float svmx;
	/**
	 * Control valves rate opening time (Ta).  Typical Value = 0.8.
	 */
	public Seconds ta;
	/**
	 * Intercept valves rate opening time (Tam).  Typical Value = 0.8.
	 */
	public Seconds tam;
	/**
	 * Control valves rate closing time (Tc).  Typical Value = 0.5.
	 */
	public Seconds tc;
	/**
	 * Intercept valves rate closing time (Tcm).  Typical Value = 0.5.
	 */
	public Seconds tcm;
	/**
	 * Derivative time constant of pressure regulator (Tdc).  Typical Value = 90.
	 */
	public Seconds tdc;
	/**
	 * Time constant of fuel regulation (Tf1).  Typical Value = 10.
	 */
	public Seconds tf1;
	/**
	 * Time constant of steam chest (Tf2).  Typical Value = 10.
	 */
	public Seconds tf2;
	/**
	 * High pressure (HP) time constant of the turbine (Thp).  Typical Value = 0.15.
	 */
	public Seconds thp;
	/**
	 * Low pressure (LP) time constant of the turbine (Tmp).  Typical Value = 0.4.
	 */
	public Seconds tmp;
	/**
	 * Reheater  time constant of the turbine (Trh).  Typical Value = 10.
	 */
	public Seconds trh;
	/**
	 * Boiler time constant (Tv).  Typical Value = 60.
	 */
	public Seconds tv;
	/**
	 * Control valves servo time constant (Ty).  Typical Value = 0.1.
	 */
	public Seconds ty;
	/**
	 * Coefficient of linearized equations of turbine (Stodola formulation) (Y).
	 * Typical Value = 0.13.
	 */
	public PU y;
	/**
	 * Minimum control valve position (Yhpmn).  Typical Value = 0.
	 */
	public PU yhpmn;
	/**
	 * Maximum control valve position (Yhpmx).  Typical Value = 1.1.
	 */
	public PU yhpmx;
	/**
	 * Minimum intercept valve position (Ympmn).  Typical Value = 0.
	 */
	public PU ympmn;
	/**
	 * Maximum intercept valve position (Ympmx).  Typical Value = 1.1.
	 */
	public PU ympmx;

	public GovSteamFV4(){

	}
}//end GovSteamFV4