package IEC61970.Dynamics.StandardModels.TurbineGovernorDynamics;

import IEC61970.Base.Domain.Float;
import IEC61970.Base.Domain.PU;
import IEC61970.Base.Domain.ActivePower;
import IEC61970.Base.Domain.Seconds;

/**
 * Simplified model  of boiler and steam turbine with PID governor.
 * @author tsaxton
 * @version 1.0
 * @created 25-Dec-2023 8:31:59 PM
 */
public class GovSteamEU extends TurbineGovernorDynamics {

	/**
	 * Control valves rate closing limit (Chc).  Unit = PU/sec.  Typical Value = -3.3.
	 */
	public Float chc;
	/**
	 * Control valves rate opening limit (Cho).  Unit = PU/sec.  Typical Value = 0.17.
	 */
	public Float cho;
	/**
	 * Intercept valves rate closing limit (Cic).  Typical Value = -2.2.
	 */
	public PU cic;
	/**
	 * Intercept valves rate opening limit (Cio).  Typical Value = 0.123.
	 */
	public PU cio;
	/**
	 * Dead band of the frequency corrector (db1).  Typical Value = 0.
	 */
	public PU db1;
	/**
	 * Dead band of the speed governor (db2).  Typical Value = 0.0004.
	 */
	public PU db2;
	/**
	 * Maximum control valve position (Hhpmax).  Typical Value = 1.
	 */
	public PU hhpmax;
	/**
	 * Gain of the power controller (Ke).  Typical Value = 0.65.
	 */
	public PU ke;
	/**
	 * Gain of the frequency corrector (Kfcor).  Typical Value = 20.
	 */
	public PU kfcor;
	/**
	 * Fraction of total turbine output generated by HP part (Khp).  Typical Value = 0.
	 * 277.
	 */
	public PU khp;
	/**
	 * Fraction of total turbine output generated by HP part (Klp).  Typical Value = 0.
	 * 723.
	 */
	public PU klp;
	/**
	 * Gain of the speed governor (Kwcor).  Typical Value = 20.
	 */
	public PU kwcor;
	/**
	 * Base for power values (MWbase) (>0).  Unit = MW.
	 */
	public ActivePower mwbase;
	/**
	 * Maximal active power of the turbine (Pmax).  Typical Value = 1.
	 */
	public PU pmax;
	/**
	 * Maximum low pressure limit (Prhmax).  Typical Value = 1.4.
	 */
	public PU prhmax;
	/**
	 * Intercept valves transfer limit (Simx).  Typical Value = 0.425.
	 */
	public PU simx;
	/**
	 * Boiler time constant (Tb).  Typical Value = 100.
	 */
	public Seconds tb;
	/**
	 * Derivative time constant of the power controller (Tdp).  Typical Value = 0.
	 */
	public Seconds tdp;
	/**
	 * Electro hydraulic transducer (Ten).  Typical Value = 0.1.
	 */
	public Seconds ten;
	/**
	 * Frequency transducer time constant (Tf).  Typical Value = 0.
	 */
	public Seconds tf;
	/**
	 * Time constant of the power controller (Tfp).  Typical Value = 0.
	 */
	public Seconds tfp;
	/**
	 * High pressure (HP) time constant of the turbine (Thp).  Typical Value = 0.31.
	 */
	public Seconds thp;
	/**
	 * Integral time constant of the power controller (Tip).  Typical Value = 2.
	 */
	public Seconds tip;
	/**
	 * Low pressure(LP) time constant of the turbine (Tlp).  Typical Value = 0.45.
	 */
	public Seconds tlp;
	/**
	 * Power transducer time constant (Tp).  Typical Value = 0.07.
	 */
	public Seconds tp;
	/**
	 * Reheater  time constant of the turbine (Trh).  Typical Value = 8.
	 */
	public Seconds trh;
	/**
	 * Control valves servo time constant (Tvhp).  Typical Value = 0.1.
	 */
	public Seconds tvhp;
	/**
	 * Intercept valves servo time constant (Tvip).  Typical Value = 0.15.
	 */
	public Seconds tvip;
	/**
	 * Speed transducer time constant (Tw).  Typical Value = 0.02.
	 */
	public Seconds tw;
	/**
	 * Upper limit for frequency correction (Wfmax).  Typical Value = 0.05.
	 */
	public PU wfmax;
	/**
	 * Lower limit for frequency correction (Wfmin).  Typical Value = -0.05.
	 */
	public PU wfmin;
	/**
	 * Emergency speed control lower limit (wmax1).  Typical Value = 1.025.
	 */
	public PU wmax1;
	/**
	 * Emergency speed control upper limit (wmax2).  Typical Value = 1.05.
	 */
	public PU wmax2;
	/**
	 * Upper limit for the speed governor (Wwmax).  Typical Value = 0.1.
	 */
	public PU wwmax;
	/**
	 * Lower limit for the speed governor frequency correction (Wwmin).  Typical Value
	 * = -1.
	 */
	public PU wwmin;

	public GovSteamEU(){

	}
}//end GovSteamEU