#######################################################
# 
# BankAccount.py
# Python implementation of the Class BankAccount
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 6:12:00 PM
# Original author: T. Kostic
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61968.Common.Document import Document
from CIM_STD_PYTHON.TC57CIM.IEC61968.InfIEC61968.InfCommon.Bank import Bank


class BankAccount(Document):
    """Bank account.
    """
    # Bank that provides this BankAccount.

    def __init__(self):
        super().__init__()
        self.bank = Bank()
