#######################################################
# 
# DCBaseTerminal.py
# Python implementation of the Class DCBaseTerminal
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:55 PM
# Original author: selaost1
# 
#######################################################
from IEC61970.Base.DC.DCTopologicalNode import DCTopologicalNode
from IEC61970.Base.Core.ACDCTerminal import ACDCTerminal

class DCBaseTerminal(ACDCTerminal):
    """An electrical connection point at a piece of DC conducting equipment. DC
    terminals are connected at one physical DC node that may have multiple DC
    terminals connected. A DC node is similar to an AC connectivity node. The model
    enforces that DC connections are distinct from AC connections.
    """
    # See association end Terminal.TopologicalNode.
    DCTopologicalNode= DCTopologicalNode()
