#######################################################
# 
# MeasurementConfigurationStatus.py
# Python implementation of the Class MeasurementConfigurationStatus
# Generated by Enterprise Architect
# Created on:      18-Dec-2023 6:13:08 PM
# Original author: selaost1
# 
#######################################################
from enum import Enum


class MeasurementConfigurationStatus(Enum):

    OK = 1
    UNKNOWN = 2
    ERROR = 3