#######################################################
# 
# ActivityRecord.py
# Python implementation of the Class ActivityRecord
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:18 PM
# 
#######################################################
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class ActivityRecord(IdentifiedObject):
    """Records activity for an entity at a point in time; activity may be for an event
    that has already occurred or for a planned activity.
    """
    pass
