#######################################################
# 
# ConfigurationEvent.py
# Python implementation of the Class ConfigurationEvent
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:20 PM
# Original author: T. Kostic
# 
#######################################################
from IEC61970.Base.Faults.FaultCauseType import FaultCauseType
from IEC61968 import ActivityRecord

class ConfigurationEvent(ActivityRecord):
    """Used to report details on creation, change or deletion of an entity or its
    configuration.
    """
    FaultCauseType= FaultCauseType()
