#######################################################
# 
# DocumentPersonRole.py
# Python implementation of the Class DocumentPersonRole
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:21 PM
# 
#######################################################
from java.IEC61968.Common import PersonRole

class DocumentPersonRole(PersonRole):
    """Person role with respect to documents.
    """
    pass
