#######################################################
# 
# Hazard.py
# Python implementation of the Class Hazard
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:22 PM
# 
#######################################################
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class Hazard(IdentifiedObject):
    """An object or a condition that is a danger for causing loss or perils to an
    asset and/or people.
    """
    pass
