#######################################################
# 
# OrganisationRole.py
# Python implementation of the Class OrganisationRole
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:23 PM
# Original author: T. Kostic
# 
#######################################################
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from java.IEC61968.Common.ConfigurationEvent import ConfigurationEvent
from java.IEC61968.Common import Organisation

class OrganisationRole(IdentifiedObject):
    """Identifies a way in which an organisation may participate in the utility
    enterprise (e.g., customer, manufacturer, etc).
    """
    # All configuration events created for this organisation role.
    ConfigurationEvents= ConfigurationEvent()

    # Organisation having this role.
    Organisation= Organisation()
