#######################################################
# 
# Status.py
# Python implementation of the Class Status
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:24 PM
# 
#######################################################
from IEC61970.Base.Domain.DateTime import DateTime
from IEC61970.Base.Domain.String import String

class Status:
    """Current status information relevant to an entity.
    """
    pass
