#######################################################
# 
# TimePoint.py
# Python implementation of the Class TimePoint
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:25 PM
# 
#######################################################
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class TimePoint(IdentifiedObject):
    """A point in time within a sequence of points in time relative to a time schedule.
    """
    pass
