# Converted by an OPENAI API call using model: gpt-3.5-turbo-1106
# der_parameter_kind.py

from enum import Enum

class DERParameterKind(Enum):
    APPARENT_POWER = 1
    ACTIVE_POWER = 2
    REACTIVE_POWER = 3
    HIGH_FILTER_BI_DIRECTIONAL_REGULATION = 4
    LOW_FILTER_BI_DIRECTIONAL_REGULATION = 5
    HIGH_FILTER_UP_REGULATION = 6
    LOW_FILTER_UP_REGULATION = 7
    HIGH_FILTER_DOWN_REGULATION = 8
    LOW_FILTER_DOWN_REGULATION = 9
    INCREASING_RAMP_RATE = 10
    DECREASING_RAMP_RATE = 11
    VOLTAGE = 12
