#######################################################
# 
# CalculationMethodHierarchy.py
# Python implementation of the Class CalculationMethodHierarchy
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:19 PM
# Original author: herb
# 
#######################################################
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from IEC61970.Base.Meas.MeasurementValue import MeasurementValue

class CalculationMethodHierarchy(IdentifiedObject):
    """The hierarchy of calculation methods used to derive this measurement.
    """
    MeasurementValue= MeasurementValue()
