#######################################################
# 
# ContingencyElement.py
# Python implementation of the Class ContingencyElement
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 7:36:35 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class ContingencyElement(IdentifiedObject):
    """An element of a system event to be studied by contingency analysis,
    representing a change in status of a single piece of equipment.
    """
    def __init__(self):
        super().__init__()

