#######################################################
# 
# AnalogToDigitalLogicKind.py
# Python implementation of the Class AnalogToDigitalLogicKind
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:54 PM
# Original author: sveinols
# 
#######################################################


class AnalogToDigitalLogicKind:
    """Categories of analog to digital (or logical result) comparison.
    """
    pass
