#######################################################
# 
# CalculationKind.py
# Python implementation of the Class CalculationKind
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:54 PM
# Original author: sveinols
# 
#######################################################


class CalculationKind:
    """Categorisation of calculation operation that can be done to Measurement.
    """
    pass
