#######################################################
# 
# GateInputPin.py
# Python implementation of the Class GateInputPin
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:58 PM
# Original author: sveinols
# 
#######################################################
from IEC61970.Base.Domain.Boolean import Boolean
from IEC61970.InfIEC61970.InfSIPS.AnalogToDigitalLogicKind import AnalogToDigitalLogicKind
from IEC61970.Base.Domain.Seconds import Seconds
from IEC61970.Base.Domain.PerCent import PerCent
from IEC61970.Base.Domain.Float import Float
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class GateInputPin(IdentifiedObject):
    """Input pin for a logical gate. The condition described in the input pin will
    give a logical true or false. Result from measurement and calculation are
    converted to a true or false.
    """
    pass
