#######################################################
# 
# GateLogicKind.py
# Python implementation of the Class GateLogicKind
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:58 PM
# Original author: sveinols
# 
#######################################################


class GateLogicKind:
    """Define the different logical operations.
    """
    pass
