#######################################################
# 
# PinBranchGroupKind.py
# Python implementation of the Class PinBranchGroupKind
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:01 PM
# Original author: sveinols
# 
#######################################################


class PinBranchGroupKind:
    """Categorisation of type of compare done on a branch group.
    """
    pass
