#######################################################
# 
# PinEquipmentKind.py
# Python implementation of the Class PinEquipmentKind
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:01 PM
# Original author: sveinols
# 
#######################################################


class PinEquipmentKind:
    """Categorisation of type of compare done on Equipment.
    """
    pass
