#######################################################
# 
# PinEquipment.py
# Python implementation of the Class PinEquipment
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:01 PM
# Original author: sveinols
# 
#######################################################
from IEC61970.InfIEC61970.InfSIPS.PinEquipmentKind import PinEquipmentKind
from IEC61970.Base.Core.Equipment import Equipment
from IEC61970.InfIEC61970.InfSIPS.GateInputPin import GateInputPin

class PinEquipment(GateInputPin):
    """Value associated with Equipment is used as compare.
    """
    Equipment= Equipment()
