#######################################################
# 
# PinGate.py
# Python implementation of the Class PinGate
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:01 PM
# Original author: sveinols
# 
#######################################################
from IEC61970.InfIEC61970.InfSIPS.GateInputPin import GateInputPin

class PinGate(GateInputPin):
    """An output from one gate represent an input to another gate.
    """
    pass
