#######################################################
# 
# PinTerminalKind.py
# Python implementation of the Class PinTerminalKind
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:01 PM
# Original author: sveinols
# 
#######################################################


class PinTerminalKind:
    """Categorisation of type of compare done on Terminal.
    """
    pass
