#######################################################
# 
# PinTerminal.py
# Python implementation of the Class PinTerminal
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:01 PM
# Original author: sveinols
# 
#######################################################
from IEC61970.InfIEC61970.InfSIPS.PinTerminalKind import PinTerminalKind
from IEC61970.Base.Core.Terminal import Terminal
from IEC61970.InfIEC61970.InfSIPS.GateInputPin import GateInputPin

class PinTerminal(GateInputPin):
    """Value associated with Terminal is used as compare.
    """
    Terminal= Terminal()
