#######################################################
# 
# ProtectiveActionRegulation.py
# Python implementation of the Class ProtectiveActionRegulation
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:02 PM
# Original author: sveinols
# 
#######################################################
from IEC61970.Base.Domain.Boolean import Boolean
from IEC61970.Base.Domain.Float import Float
from IEC61970.Base.Wires.RegulatingControl import RegulatingControl
from IEC61970.InfIEC61970.InfSIPS.ProtectiveAction import ProtectiveAction

class ProtectiveActionRegulation(ProtectiveAction):
    """Protective action to change regulation to Equipment.
    """
    RegulatingControl= RegulatingControl()
