#######################################################
# 
# ProtectiveActionAdjustmentKind.py
# Python implementation of the Class ProtectiveActionAdjustmentKind
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:02 PM
# Original author: sveinols
# 
#######################################################


class ProtectiveActionAdjustmentKind:
    """Categorisation of different protective action adjustments that can be performed
    on equipment.
    """
    pass
