#######################################################
# 
# ProtectiveActionAdjustment.py
# Python implementation of the Class ProtectiveActionAdjustment
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:02 PM
# Original author: sveinols
# 
#######################################################
from IEC61970.Base.Domain.PerCent import PerCent
from IEC61970.Base.Domain.Float import Float
from IEC61970.InfIEC61970.InfSIPS.ProtectiveActionAdjustmentKind import ProtectiveActionAdjustmentKind
from IEC61970.Base.Domain.Boolean import Boolean
from IEC61970.Base.DC.DCConductingEquipment import DCConductingEquipment
from IEC61970.InfIEC61970.InfSIPS.ProtectiveAction import ProtectiveAction

class ProtectiveActionAdjustment(ProtectiveAction):
    """Protective actions on non-switching equipment. The operating condition is
    adjusted.
    """
    DCConductingEquipment= DCConductingEquipment()
