#######################################################
# 
# ProtectiveActionCollection.py
# Python implementation of the Class ProtectiveActionCollection
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:02 PM
# Original author: sveinols
# 
#######################################################
from IEC61970.InfIEC61970.InfSIPS.StageTrigger import StageTrigger
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from IEC61970.InfIEC61970.InfSIPS.ProtectiveAction import ProtectiveAction

class ProtectiveActionCollection(IdentifiedObject):
    """A collection of protective actions to protect the integrity of the power system.
    """
    StageTrigger= StageTrigger()

    ProtectiveAction= ProtectiveAction()
