#######################################################
# 
# ProtectiveAction.py
# Python implementation of the Class ProtectiveAction
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:02 PM
# Original author: sveinols
# 
#######################################################
from IEC61970.Base.Domain.Boolean import Boolean
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from IEC61970.InfIEC61970.InfSIPS.Gate import Gate

class ProtectiveAction(IdentifiedObject):
    """A protective action for supporting the integrity of the power system.
    """
    GateComCondition= Gate()

    GateEnabledCondition= Gate()
