#######################################################
# 
# RemedialActionScheme.py
# Python implementation of the Class RemedialActionScheme
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:03 PM
# Original author: sveinols
# 
#######################################################
from IEC61970.Base.Domain.Boolean import Boolean
from IEC61970.InfIEC61970.InfSIPS.RemedialActionSchemeKind import RemedialActionSchemeKind
from IEC61970.Base.Core.PowerSystemResource import PowerSystemResource
from IEC61970.InfIEC61970.InfSIPS.Stage import Stage

class RemedialActionScheme(PowerSystemResource):
    """Remedial Action Scheme (RAS), Special Protection Schemes (SPS), System
    Protection Schemes (SPS) or System Integrity Protection Schemes (SIPS).
    """
    Stage= Stage()
