#######################################################
# 
# RemedialActionSchemeKind.py
# Python implementation of the Class RemedialActionSchemeKind
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:03 PM
# Original author: sveinols
# 
#######################################################


class RemedialActionSchemeKind:
    """Classification of Remedial Action Scheme.
    """
    pass
