#######################################################
# 
# BlockDispatchComponent.py
# Python implementation of the Class BlockDispatchComponent
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:54 PM
# Original author: selaost1
# 
#######################################################
from IEC61970.InfIEC61970.EnergyArea.EnergyComponent import EnergyComponent

class BlockDispatchComponent(EnergyComponent):
    pass
