#######################################################
# 
# BlockDispatchOrder.py
# Python implementation of the Class BlockDispatchOrder
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:54 PM
# Original author: selaost1
# 
#######################################################
from IEC61970.Base.Domain.ActivePower import ActivePower
from IEC61970.Base.Domain.Integer import Integer
from IEC61970.InfIEC61970.EnergyArea.BlockDispatchComponent import BlockDispatchComponent
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class BlockDispatchOrder(IdentifiedObject):
    m_BlockDispatchComponent= BlockDispatchComponent()
