#######################################################
# 
# BoundaryFlow.py
# Python implementation of the Class BoundaryFlow
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:54 PM
# Original author: selaost1
# 
#######################################################
from IEC61970.Base.Domain.Boolean import Boolean
from IEC61970.InfIEC61970.EnergyArea.EnergySchedulingAreaBoundary import EnergySchedulingAreaBoundary
from IEC61970.Base.Core.Terminal import Terminal
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class BoundaryFlow(IdentifiedObject):
    m_EnergySchedulingAreaBoundary= EnergySchedulingAreaBoundary()

    m_Terminal= Terminal()
