#######################################################
# 
# EnergyComponent.py
# Python implementation of the Class EnergyComponent
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:56 PM
# Original author: selaost1
# 
#######################################################
from IEC61970.InfIEC61970.EnergyArea.EnergyGroup import EnergyGroup
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class EnergyComponent(IdentifiedObject):
    m_EnergyGroup= EnergyGroup()
