#######################################################
# 
# EnergyAreaTypeKind.py
# Python implementation of the Class EnergyAreaTypeKind
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:56 PM
# Original author: selaost1
# 
#######################################################


class EnergyAreaTypeKind:
    pass
