#######################################################
# 
# EnergySchedulingArea.py
# Python implementation of the Class EnergySchedulingArea
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:56 PM
# Original author: selaost1
# 
#######################################################
from IEC61970.Base.Domain.ActivePower import ActivePower
from IEC61970.Base.Domain.Float import Float
from IEC61970.InfIEC61970.EnergyArea.EnergyAreaTypeKind import EnergyAreaTypeKind
from IEC61970.InfIEC61970.EnergyArea.EnergySchedulingAreaBoundary import EnergySchedulingAreaBoundary
from IEC61970.Base.Core.PowerSystemResource import PowerSystemResource

class EnergySchedulingArea(PowerSystemResource):
    m_EnergySchedulingAreaBoundary= EnergySchedulingAreaBoundary()
