#######################################################
# 
# EnergyTypeReference.py
# Python implementation of the Class EnergyTypeReference
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:56 PM
# Original author: selaost1
# 
#######################################################
from IEC61970.InfIEC61970.EnergyArea.EnergyTypeKind import EnergyTypeKind
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class EnergyTypeReference(IdentifiedObject):
    pass
