#######################################################
# 
# EnergySchedulingAreaBoundary.py
# Python implementation of the Class EnergySchedulingAreaBoundary
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:56 PM
# Original author: selaost1
# 
#######################################################
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class EnergySchedulingAreaBoundary(IdentifiedObject):
    pass
