#######################################################
# 
# EnergyGroup.py
# Python implementation of the Class EnergyGroup
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:56 PM
# Original author: selaost1
# 
#######################################################
from IEC61970.Base.Domain.Boolean import Boolean
from IEC61970.Base.Domain.ActivePower import ActivePower
from IEC61970.InfIEC61970.EnergyArea.EnergyTypeReference import EnergyTypeReference
from IEC61970.InfIEC61970.EnergyArea.EnergySchedulingArea import EnergySchedulingArea
from IEC61970.Base.Core.PowerSystemResource import PowerSystemResource

class EnergyGroup(PowerSystemResource):
    m_EnergyTypeReference= EnergyTypeReference()

    m_EnergySchedulingArea= EnergySchedulingArea()
