#######################################################
# 
# ProportionalDistributionComponent.py
# Python implementation of the Class ProportionalDistributionComponent
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:02 PM
# Original author: selaost1
# 
#######################################################
from IEC61970.Base.Domain.ActivePower import ActivePower
from IEC61970.InfIEC61970.EnergyArea.EnergyComponent import EnergyComponent

class ProportionalDistributionComponent(EnergyComponent):
    pass
