#######################################################
# 
# ActivePower.py
# Python implementation of the Class ActivePower
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 6:46:22 PM
# 
#######################################################
from IEC61970.Base.Domain.UncefactUnitCode import UncefactUnitCode
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol


class ActivePower:
    """
    Product of RMS value of the voltage and the RMS value of the in-phase component
    of the current.
    """
    def __init__(self, v=0.0):
        self.multiplier = UnitMultiplier()  # The unit multiplier for the active power value
        self.uncefact_unit_code = UncefactUnitCode()  # The UN/CEFACT unit code for the active power value
        self.value: float = v  # The numerical value of the active power
        self.unit = UnitSymbol().W  # Static constant unit symbol for active power