#######################################################
# 
# ActivePower.py
# Python implementation of the Class ActivePower
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 6:46:22 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UncefactUnitCode import UncefactUnitCode
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol


class ActivePower:
    """Product of RMS value of the voltage and the RMS value of the in-phase component
    of the current.
    """

    unit = UnitSymbol().W  # Static constant unit symbol for active power

    def __init__(self):
        self.multiplier = UnitMultiplier()  # The unit multiplier for the active power value
        self.uncefact_unit_code = UncefactUnitCode()  # The UN/CEFACT unit code for the active power value
        self.value: float = 0.0  # The numerical value of the active power
