#######################################################
# AngleDegrees.py
# Python implementation of the Class AngleDegrees
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 7:58:41 PM
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
# from IEC61970.Base.Domain.Float import Float


class AngleDegrees:
    """
    Measurement of angle in degrees.
    """
    def __init__(self, v=None):
        self.unit = UnitSymbol.deg
        self.multiplier = UnitMultiplier.none
        self.value = v
