#######################################################
# 
# ApparentPower.py
# Python implementation of the Class ApparentPower
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 7:53:18 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UncefactUnitCode import UncefactUnitCode
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol


class ApparentPower:
    """Product of the RMS value of the voltage and the RMS value of the current.
    """

    def __init__(self):
        self.value = 0.0
        self.mutiplier = UnitMultiplier.none
        self.uncfact_unit_code = UncefactUnitCode()
        self.unit = UnitSymbol.VA
