#######################################################
# 
# Capacitance.py
# Python implementation of the Class Capacitance
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 8:56:43 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol


class Capacitance:
    """Capacitive part of reactance (imaginary part of impedance), at rated frequency.
    """
    unit = UnitSymbol.F

    def __init__(self):
        self.value = 0.0
        self.multiplier = UnitMultiplier.none