#######################################################
# 
# DateTime.py
# Python implementation of the Class DateTime
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 10:07:20 PM
# 
#######################################################


class DateTime:
    """Date and time as "yyyy-mm-ddThh:mm:ss.sss", which conforms with ISO 8601. UTC
    time zone is specified as "yyyy-mm-ddThh:mm:ss.sssZ". A local timezone relative
    UTC is specified as "yyyy-mm-ddThh:mm:ss.sss-hh:mm". The second component
    (shown here as "ss.sss") could have any number of digits in its fractional part
    to allow any kind of precision beyond seconds.
    """
    pass
