#######################################################
# 
# Frequency.py
# Python implementation of the Class Frequency
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 10:55:21 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol


class Frequency:
    """
    Cycles per second.
    """

    def __init__(self, v=0.0):
        self.multiplier = UnitMultiplier.none
        self.value = v
        self.unit = UnitSymbol.Hz