#######################################################
# 
# Impedance.py
# Python implementation of the Class Impedance
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 10:57:42 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol

class Impedance:
    """Ratio of voltage to current.
    """
    unit = UnitSymbol.ohm
    def __init__(self):
        self.value = 0.0
        self.multipler = UnitMultiplier.none