#######################################################
# 
# KiloActivePower.py
# Python implementation of the Class KiloActivePower
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 11:09:20 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol


class KiloActivePower:
    """Active power in kilowatts.
    """
    unit = UnitSymbol.W

    def __init__(self) -> None:
        self.multiplier: UnitMultiplier = UnitMultiplier.k
        self.value: float = 0.0