#######################################################
# 
# Length.py
# Python implementation of the Class Length
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 11:12:20 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol


class Length:
    """Unit of length. Never negative.
    """
    unit = UnitSymbol.M

    def __init__(self) -> None:
        self.multiplier: UnitMultiplier = UnitMultiplier.none
        self.value: float = 0.0