#######################################################
# 
# Money.py
# Python implementation of the Class Money
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 11:12:00 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Currency import Currency
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol


class Money:
    """Amount of money.
    """
    unit = UnitSymbol.none
    def __init__(self):

        self.multiplier = UnitMultiplier.none
        self.value: Currency = Currency()