#######################################################
# 
# PU.py
# Python implementation of the Class PU
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 11:21:07 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol


class PU:
    """Per Unit - a positive or negative value
    referred to a defined base. Values typically range from -10 to +10.
    """
    def __init__(self, v=None):
        self.multiplier = UnitMultiplier.none
        self.value = v
        self.unit = UnitSymbol.none

