#######################################################
# 
# ReactivePower.py
# Python implementation of the Class ReactivePower
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 11:25:22 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol


class ReactivePower:
    """Product of RMS value of the voltage and the RMS value of the quadrature
    component of the current.
    """
    unit = UnitSymbol.VAr

    def __init__(self):
        self.multiplier = UnitMultiplier.none
        self.value = 0.0