#######################################################
# 
# RealEnergy.py
# Python implementation of the Class RealEnergy
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 11:25:39 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UncefactUnitCode import UncefactUnitCode
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol


class RealEnergy:
    """Real electrical energy.
    """
    unit = UnitSymbol.Wh

    def __init__(self):
        self.value = 0.0
        self.multiplier = UnitMultiplier.none
        self.uncefact_unit_code = UncefactUnitCode()
