#######################################################
# 
# Resistance.py
# Python implementation of the Class Resistance
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 11:25:59 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol


class Resistance:
    """Resistance (real part of impedance).
    """
    unit = UnitSymbol.ohm

    def __init__(self):
        self.multiplier = UnitMultiplier.none
        self.value = 0.0
