#######################################################
# 
# StringQuantity.py
# Python implementation of the Class StringQuantity
# Generated by Enterprise Architect
# Created on:      20-Dec-2023 5:44:26 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol


class StringQuantity:
    """Quantity with string value (when it is not important whether it is an integral
    or a floating point number) and associated unit information.
    """
    unit_symbol = UnitSymbol.none
    def __init__(self):
        self.unit_mulitplier = UnitMultiplier.none
        self.value = ""