#######################################################
# 
# Susceptance.py
# Python implementation of the Class Susceptance
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 11:27:27 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol


class Susceptance:
    """Imaginary part of admittance.
    """

    def __init__(self):
        self.multiplier = UnitMultiplier.none
        self.value = 0.0
        self.unit = UnitSymbol.S
