#######################################################
# 
# UnitSymbol.py
# Python implementation of the Class UnitSymbol
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 8:56:51 PM
# 
#######################################################


class UnitSymbol:

    # """
    # The derived units defined for usage in the CIM. In some cases, the derived unit
    # is equal to an SI unit. Whenever possible, the standard derived symbol is used
    # instead of the formula for the derived unit. For example, the unit symbol Farad
    # is defined as "F" instead of "CPerV". In cases where a standard symbol does not
    # exist for a derived unit, the formula for the unit is used as the unit symbol.
    # For example, density does not have a standard symbol and so it is represented
    # as "kgPerm3". With the exception of the "kg", which is an SI unit, the unit
    # symbols do not contain multipliers and therefore represent the base derived
    # unit to which a multiplier can be applied as a whole.
    #
    #   Every unit symbol is treated as an unparseable text as if it were a single-
    # letter symbol. The meaning of each unit symbol is defined by the accompanying
    # descriptive text and not by the text contents of the unit symbol.
    #
    #   To allow the widest possible range of serializations without requiring
    # special character handling, several substitutions are made which deviate from
    # the format described in IEC 80000-1. The division symbol "/" is replaced by the
    # letters"Per". Exponents are written in plain text after the unit as "m3"
    # instead of being formatted as in "m<sup>3</sup>" or introducing a symbol as in
    # "m^3". The degree symbol "°" is replaced with the letters "deg". Any
    # clarification of the meaning for a substitution is included in the description
    # for the unit symbol.
    #
    #   Non-SI units are included in list of unit symbols to allow sources of data to
    # be correctly labeled with their non-SI units (for example, a GPS sensor that is
    # reporting numbers that represent feet instead of meters). This allows software
    # to use the unit symbol information correctly convert and scale the raw data of
    # those sources into SI-based units.
    #
    # """

    # Dimension less quantity, e.g. count, per unit, etc.
    none = 0

    m = 2  # Length in meter.

    kg = 3  # Mass in kilogram.
    # Note: multiplier “k” is included in this unit symbol for
    # compatibility with IEC 61850-7-3.
    s = 4  # Time in seconds.
    A = 5  # Current in Ampere.
    K = 6  # Temperature in Kelvin.
    mol = 7  # Amount of substance in mole.
    cd = 8  # Luminous intensity in candela.
    deg = 9  # Plane angle in degrees.
    rad = 10  # Plane angle in radian (m/m).
    sr = 11  # Solid angle in steradian (m2/m2).
    Gy = 21  # Absorbed dose in Gray (J/kg).
    Bq = 22  # Radioactivity in Becquerel (1/s).
    degC = 23  # Relative temperature in degrees Celsius.
    # In the SI unit system the symbol is ºC. Electric charge is measured in coulomb
    # that has the unit symbol C. To distinguish degree Celsius form coulomb the
    # symbol used in the UML is degC. Reason for not using ºC is the special
    # character º is difficult to manage in software.
    Sv = 24  # Dose equivalent in Sievert (J/kg).
    F = 25  # Electric capacitance in Farad (C/V).
    C = 26  # Electric charge in Coulomb (A·s).
    S = 27  # Conductance in Siemens.
    H = 28  # Electric inductance in Henry (Wb/A).
    V = 29  # Electric potential in Volt (W/A).
    ohm = 30  # Electric resistance in ohm (V/A).
    J = 31  # Energy in joule (N·m = C·V = W·s).
    N = 32  # Force in Newton (kg·m/s²).
    Hz = 33  # Frequency in Hertz (1/s).
    lx = 34  # Illuminance in lux (lm/m²).
    lm = 35  # Luminous flux in lumen (cd·sr).
    Wb = 36  # Magnetic flux in Weber (V·s).
    T = 37  # Magnetic flux density in Tesla (Wb/m2).
    W = 38  # Real power in Watt (J/s).
    # Electrical power may have real and reactive
    # components. The real portion of electrical power (I²R or VIcos(phi)), is
    # expressed in Watts. (See also apparent power and reactive power.)
    Pa = 39  # Pressure in Pascal (N/m²).
    # Note: the absolute or relative measurement of
    # pressure is implied with this entry. See below for more explicit forms.
    m2 = 41  # Area in square metre (m²).
    m3 = 42  # Volume in cubic metre (m³).
    mPers = 43  # Velocity in metre per second (m/s).
    mPers2 = 44  # Acceleration in metre per second squared (m/s²).
    m3Pers = 45  # Volumetric flow rate in cubic metres per second (m³/s).
    mPerm3 = 46  # Fuel efficiency in metre per cubic metre (m/m³).
    kgm = 47  # Moment of mass in kilogram metre (kg·m)  (first moment of mass).
    #  Note: multiplier “k” is included in this unit symbol for compatibility with IEC 61850-
    # 7-3.
    kgPerm3 = 48  # Density in kilogram/cubic metre (kg/m³).
    #  Note: multiplier “k” is included in this unit symbol for compatibility with IEC 61850-7-3.
    WPermK = 50  # Thermal conductivity in Watt/metre Kelvin.
    JPerK = 51  # Heat capacity in Joule/Kelvin.
    ppm = 52  # Concentration in parts per million.
    rotPers = 53  # Rotations per second (1/s). See also Hz (1/s).
    radPers = 54  # Angular velocity in radians per second (rad/s).
    VA = 61  # Apparent power in Volt Ampere (See also real power and reactive power.)
    VAr = 63  # Reactive power in Volt Ampere reactive.
    # The “reactive” or “imaginary” component
    # of electrical power (VIsin(phi)). (See also real power and apparent power).
    # Note: Different meter designs use different methods to arrive at their results.
    # Some meters may compute reactive power as an arithmetic value, while others
    # compute the value vectorially. The data consumer should determine the method in
    # use and the suitability of the measurement for the intended purpose.
    cosPhi = 65  # Power factor, dimensionless.
    # Note 1: This definition of power factor only holds for balanced systems. See
    # the alternative definition under code 153.
    # Note 2: Beware of differing sign conventions in use between the IEC and EEI.
    # It is assumed that the data consumer understands the type of meter in use and
    # the sign convention in use by the utility.
    Vs = 66  # Volt second (Ws/A).
    V2 = 67  # Volt squared (W²/A²).
    As = 68  # Ampere seconds (A·s).
    A2 = 69  # Ampere squared (A²).
    A2s = 70  # Ampere squared time in square ampere (A²s).
    VAh = 71  # Apparent energy in Volt Ampere hours.
    Wh = 72  # Real energy in Watt hours.
    VArh = 73  # Reactive energy in Volt Ampere reactive hours.
    VPerHz = 74  # Magnetic flux in Volt per Hertz.
    HzPers = 75  # Rate of change of frequency in Hertz per second.
    character = 76  # Number of characters.
    charPers = 77  # Data rate (baud) in characters per second.
    kgm2 = 78  # Moment of mass in kilogram square metre (kg·m²) (Second moment of mass,
    # commonly called the moment of inertia).
    #  Note: multiplier “k” is included in
    # this unit symbol for compatibility with IEC 61850-7-3.
    dB = 79  # Sound pressure level in decibel.
    #  Note:  multiplier “d” is included in this unit
    #     # symbol for compatibility with IEC 61850-7-3.
    WPers = 81  # Ramp rate in Watt per second.
    lPers = 82  # Volumetric flow rate in litre per second.
    dBm = 83  # Power level (logrithmic ratio of signal strength , Bel-mW), normalized to 1mW.
    # Note:  multiplier “d” is included in this unit symbol for compatibility with
    # IEC 61850-7-3.
    h = 84  # Time, hour = 60 min = 3600 s.
    min = 85  # Time, minute  = 60 s,
    Q = 100  # Quantity power, Q.
    Qh = 101  # Quantity energy, Qh.
    ohmm = 102  # resistivity, Ohm metre, (rho).
    APerm = 103  # A/m, magnetic field strength, Ampere per metre.
    V2h = 104  # volt-squared hour, Volt-squared-hours.
    A2h = 105  # ampere-squared hour, Ampere-squared hour.
    Ah = 106  # Ampere-hours, Ampere-hours.
    count = 111  # Amount of substance, Counter value.
    ft3 = 119  # Volume, cubic foot.
    m3Perh = 125  # Volumetric flow rate, cubic metre per hour.
    gal = 128  # Volume, US gallon (1 gal = 231 in3 = 128 fl ounce).
    Btu = 132  # Energy, British Thermal Unit.
    l = 134  # Volume, litre = dm3 = m3/1000.
    lPerh = 137  # Volumetric flow rate, litre per hour.
    lPerl = 143  # Concentration,
    # The ratio of the volume of a solute divided by the volume of
    # the solution. Note: Users may need use a prefix such a ‘µ’ to express a
    # quantity such as ‘µL/L’.
    gPerg = 144  # Concentration,
    #  The ratio of the mass of a solute divided by the mass of  the
    # solution. Note: Users may need use a prefix such a ‘µ’ to express a quantity
    # such as ‘µg/g’.
    molPerm3 = 145  # Concentration
    # The amount of substance concentration, (c), the amount of
    # solvent in moles divided by the volume of solution in m³.
    molPermol = 146  # Concentration,
    # Molar fraction (?), the ratio of the molar amount of a solute
    # divided by the molar amount of the solution.
    molPerkg = 147  # Concentration
    # Molality, the amount of solute in moles and the amount of
    # solvent in kilograms.
    sPers = 149  # Time, Ratio of time
    # Time, Ratio of time Note: Users may need to supply a prefix such as ‘µ’ to show rates such as ‘µs/s’
    HzPerHz = 150  # Frequency, Rate of frequency change
    #Note: Users may need to supply a prefix such as ‘m’ to show rates such as ‘mHz/Hz’.
    VPerV = 151  # Voltage, Ratio of voltages
    # Note: Users may need to supply a prefix such as ‘m’
    # to show rates such as ‘mV/V’.
    APerA = 152  # Current, Ratio of Amperages
    #  Note: Users may need to supply a prefix such as
    # ‘m’ to show rates such as ‘mA/A’.
    VPerVA = 153  # Power factor, PF, the ratio of the active power to the apparent power.
    # Note: The sign convention used for power factor will differ between IEC meters and
    # EEI (ANSI) meters. It is assumed that the data consumers understand the type of
    # meter being used and agree on the sign convention in use at any given utility.
    rev = 154  # Amount of rotation, Revolutions.
    kat = 158  # Catalytic activity, katal = mol / s.
    JPerkg = 165  # Specific energy, Joule / kg.
    m3Uncompensated = 166  # Volume, cubic metre, with the value uncompensated for weather effects.
    m3Compensated = 167  # Volume, cubic metre, with the value compensated for weather effects.
    WPerW = 168  # Signal Strength, Ratio of power
    # Note: Users may need to supply a prefix such
    # as ‘m’ to show rates such as ‘mW/W’.
    therm = 169  # Energy, Therm.
    onePerm = 173  # Wavenumber, reciprocal metre,  (1/m).
    m3Perkg = 174  # Specific volume, cubic metre per kilogram, v.
    Pas = 175  # Dynamic viscosity, Pascal second.
    Nm = 176  # Moment of force, Newton metre.
    NPerm = 177  # Surface tension, Newton per metre.
    radPers2 = 178  # Angular acceleration, radian per second squared.
    WPerm2 = 55  # Heat flux density, irradiance, Watt per square metre.
    JPerkgK = 60  # Specific heat capacity, specific entropy, Joule per kilogram Kelvin.
    JPerm3 = 181  # energy density, Joule per cubic metre.
    VPerm = 182  # electric field strength, Volt per metre.
    CPerm3 = 183  # electric charge density, Coulomb per cubic metre.
    CPerm2 = 184  # surface charge density, Coulomb per square metre.
    FPerm = 185  # permittivity, Farad per metre.
    HPerm = 186  # permeability, Henry per metre.
    JPermol = 187  # molar energy, Joule per mole.
    JPermolK = 188  # molar entropy, molar heat capacity, Joule per mole kelvin.
    CPerkg = 189  # exposure (x rays), Coulomb per kilogram.
    GyPers = 190  # absorbed dose rate, Gray per second.
    WPersr = 191  # Radiant intensity, Watt per steradian.
    WPerm2sr = 192  # radiance, Watt per square metre steradian.
    katPerm3 = 193  # catalytic activity concentration, katal per cubic metre.
    d = 195  # Time, day = 24 h = 86400 s.
    anglemin = 196  # Plane angle, minute.
    anglesec = 197  # Plane angle, second.
    ha = 198  # Area, hectare.
    tonne = 199  # mass, “tonne” or “metric  ton” (1000 kg = 1 Mg).
    bar = 214  # Pressure, bar (1 bar = 100 kPa).
    mmHg = 215  # Pressure, millimeter of mercury (1 mmHg is approximately 133.3 Pa).
    M = 217  # Length, nautical mile (1 M = 1852 m).
    kn = 219  # Speed, knot (1 kn = 1852/3600) m/s.
    Vh = 280  # Volt-hour, Volt hours.
    Mx = 276  # Magnetic flux, Maxwell (1 Mx = 10-8 Wb).
    G = 277  # Magnetic flux density, Gauss (1 G = 10-4 T).
    Oe = 278  # Magnetic field, Œrsted (1 Oe = (103/4p) A/m).
    SPerm = 57  # Conductance per length (F/m).
    m2Pers = 49  # Viscosity in metre square / second (m²/s).
    JPerm2 = 56  # Insulation energy density, Joule per square metre or watt second per square metre.
    KPers = 58  # Temperature change rate in Kelvin per second.
    PaPers = 59  # Pressure change rate in Pascal per second.
    ohmPerm = 300  # Ohm per meter
    VPerVAr = 159
    onePerHz = 160  # 1/Hz
