#######################################################
# 
# Voltage.py
# Python implementation of the Class Voltage
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 6:37:20 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UncefactUnitCode import UncefactUnitCode
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol


class Voltage:
    """Electrical voltage, can be both AC and DC.
    """
    unit = UnitSymbol.V  # Static constant unit symbol for voltage

    def __init__(self):
        self.multiplier = UnitMultiplier.none  # The unit multiplier for the voltage value
        self.uncefact_unit_code = UncefactUnitCode()  # The UN/CEFACT unit code for the voltage value
        self.value: float = 0.0 # The numerical value of the voltage

