#######################################################
# 
# Classification.py
# Python implementation of the Class Classification
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:55 PM
# 
#######################################################
from IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from IEC61970.Base.Domain.Integer import Integer

class Classification:
    """Classification of level.  Specify as 1..n, with 1 being the most detailed,
    highest priority, etc as described on the attribue using this data type.
    """
    multiplier = none
    unit = none