#######################################################
# 
# GeneratorControlMode.py
# Python implementation of the Class GeneratorControlMode
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:58 PM
# 
#######################################################


class GeneratorControlMode:
    """Unit control modes.
    """
    pass
