#######################################################
# 
# HydroPump.py
# Python implementation of the Class HydroPump
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:59 PM
# 
#######################################################
from IEC61970.Base.Domain.VolumeFlowRate import VolumeFlowRate
from IEC61970.Base.Domain.ActivePower import ActivePower
from IEC61970.Base.Core.Equipment import Equipment
from IEC61970.Base.Generation.Production.HydroPumpOpSchedule import HydroPumpOpSchedule

class HydroPump(Equipment):
    """A synchronous motor-driven pump, typically associated with a pumped storage
    plant.
    """
    # The hydro pump has a pumping schedule over time, indicating when pumping is to
    # occur.
    HydroPumpOpSchedule= HydroPumpOpSchedule()
