#######################################################
# 
# WindGenUnitKind.py
# Python implementation of the Class WindGenUnitKind
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:05 PM
# 
#######################################################


class WindGenUnitKind:
    """Kind of wind generating unit.
    """
    pass
