# Converted by an OPENAI API call using model: gpt-3.5-turbo-1106
from enum import Enum


class BreakerRepairItemKind(Enum):
    AIR_COMPRESSOR = 1  # "AIRCOMPRESSOR"
    AUXILIARY_SWITCH_AND_LINKAGE = 2  # "AUXILIARYSWITCHANDLINKAGE"
    BUS_CONNECTION = 3  # "BUSCONNECTION"
    CHECK_VALVE = 4  # "CHECKVALVE"
    CLOSE_COIL = 5  # "CLOSECOIL"
    CONTACTOR = 6  # "CONTACTOR"
    CONTROL_CIRCUIT = 7  # "CONTROLCIRCUIT"
    CORROSION = 8  # "CORROSION"
    GAS_DENSITY_SUPERVISION = 9  # "GASDENSITYSUPERVISION"
    HEATER_OR_THERMOSTAT = 10  # "HEATERORTHERMOSTAT"
    HYDRAULIC_FLUID_LEAK = 11  # "HYDRAULICFLUIDLEAK"
    INTERRUPTER_ASSEMBLY = 12  # "INTERRUPTERASSEMBLY"
    POSITION_INDICATOR = 13  # "POSITIONINDICATOR"
    PRESSURE_SWITCH = 14  # "PRESSURESWITCH"
    PUMP_OR_MOTOR = 15  # "PUMPORMOTOR"
    RELAY = 16  # "RELAY"
    SF6_GAS_LEAK = 17  # "SF6GASLEAK"
    STORED_ENERGY_SYSTEM = 18  # "STOREDENERGYSYSTEM"
    TRIP_COIL = 19  # "TRIPCOIL"
    TRIP_CONTROL_VALVE = 20  # "TRIPCONTROLVALVE"
    WIRING = 21  # "WIRING"
    OTHER = 22  # "OTHER"
