#######################################################
# 
# MaterialItem.py
# Python implementation of the Class MaterialItem
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 9:05:22 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject


class MaterialItem(IdentifiedObject):
    """The physical consumable supply used for work and other purposes. It includes
    items such as nuts, bolts, brackets, glue, etc.
    """
    def __init__(self):
        super().__init__()
        self.quantity = 0
