#######################################################
# 
# WorkActivityRecord.py
# Python implementation of the Class WorkActivityRecord
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 8:49:57 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61968.Common.ActivityRecord import ActivityRecord
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.PerCent import PerCent


class WorkActivityRecord(ActivityRecord):
    """Records information about the status of work or work task at a point in time.
    """
    def __init__(self):
        super().__init__()
        self.percent_complete = PerCent()
