#######################################################
# 
# CurrentTransformer.py
# Python implementation of the Class CurrentTransformer
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:31:55 PM
# 
#######################################################

from IEC61970.Base.Domain.PerCent import PerCent
from IEC61970.Base.Domain.ActivePower import ActivePower
from IEC61970.Base.AuxiliaryEquipment.Sensor import Sensor

class CurrentTransformer(Sensor):
    """Instrument transformer used to measure electrical qualities of the circuit that
    is being protected and/or monitored. Typically used as current transducer for
    the purpose of metering or protection. A typical secondary current rating would
    be 5A.
    """
    pass
