# Converted by an OPENAI API call using model: gpt-3.5-turbo-1106
from enum import Enum

class CustomerKind(Enum):
    RESIDENTIAL = 1
    RESIDENTIAL_AND_COMMERCIAL = 2
    RESIDENTIAL_AND_STREETLIGHT = 3
    RESIDENTIAL_STREETLIGHT_OTHERS = 4
    RESIDENTIAL_FARM_SERVICE = 5
    COMMERCIAL_INDUSTRIAL = 6
    PUMPING_LOAD = 7
    WIND_MACHINE = 8
    ENERGY_SERVICE_SUPPLIER = 9
    ENERGY_SERVICE_SCHEDULER = 10
    INTERNAL_USE = 11
    ENTERPRISE = 12
    REGIONAL_OPERATOR = 13
    SUBSIDIARY = 14
    OTHER = 15
