#######################################################
# 
# BasicIntervalSchedule.py
# Python implementation of the Class BasicIntervalSchedule
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 4:35:36 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class BasicIntervalSchedule(IdentifiedObject):
    """Schedule of values at points in time.
    """
    def __init__(self):
        super().__init__()
        self.start_time = DateTime()
        self.value1_multiplier = UnitMultiplier()
        self.value1_unit = UnitSymbol()
        self.value2_multiplier = UnitMultiplier()
        self.value2_unit = UnitSymbol()
