#######################################################
# 
# BreakerConfiguration.py
# Python implementation of the Class BreakerConfiguration
# Generated by Enterprise Architect
# Created on:      18-Dec-2023 3:06:17 PM
# 
#######################################################
from enum import Enum


class BreakerConfiguration(Enum):
    """Switching arrangement for bay.
    """
    BREAKER_AND_A_HALF = 1
    DOUBLE_BREAKER = 2
    NO_BREAKER = 3
    SINGLE_BREAKER = 4