#######################################################
# 
# ConductingEquipment.py
# Python implementation of the Class ConductingEquipment
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 3:43:28 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.Equipment import Equipment
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.InfSIPS.ProtectiveActionAdjustment import ProtectiveActionAdjustment


class ConductingEquipment(Equipment):
    """The parts of the AC power system that are designed to carry current or that are
    conductively connected through terminals.
    """
    # The operating condition to the Conducting Equipment is changed when protective
    # action adjustment is activated. For Shunt Compensator or other conducting
    # equipment that operates on discrete values (integer), the values given in float
    # will be rounded. 


    def __init__(self):
        super().__init__()
        self.protective_actionA_adjustment = ProtectiveActionAdjustment()
