#######################################################
# 
# ConnectivityNode.py
# Python implementation of the Class ConnectivityNode
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:34:46 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.ConnectivityNodeContainer import ConnectivityNodeContainer
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class ConnectivityNode(IdentifiedObject):
    """
    Connectivity nodes are points where terminals of AC conducting equipment are
    connected together with zero impedance.
    """

    def __init__(self):
        super().__init__()
        self.connectivity_node_container = ConnectivityNodeContainer()  # Container of this connectivity node.
