#######################################################
# 
# ConnectivityNodeContainer.py
# Python implementation of the Class ConnectivityNodeContainer
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:35:02 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.PowerSystemResource import PowerSystemResource

class ConnectivityNodeContainer(PowerSystemResource):
    """
    A base class for all objects that may contain connectivity nodes or topological
    nodes.
    """
    def __init__(self):
        super().__init__()

