#######################################################
# 
# EquipmentContainer.py
# Python implementation of the Class Equipment
# Generated by Enterprise Architect
# Created on:      16-Dec-2023 5:41:16 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.ConnectivityNodeContainer import ConnectivityNodeContainer
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.Equipment import Equipment


class EquipmentContainer(ConnectivityNodeContainer):
    """A modeling construct to provide a root class for containing equipment.
    """
    def __init__(self):
        super().__init__()
        # Contained equipment.
        self.equipments = Equipment()

        # The additonal contained equipment.  The equipment belong to the equipment
        # container. The equipment is contained in another equipment container, but also
        # grouped with this equipment container.  Examples include when a switch
        # contained in a substation is also desired to be grouped with a line contianer
        # or when a switch is included in a secondary substation and also grouped in a
        # feeder.
        self.additional_grouped_equipment = Equipment()


