#######################################################
# 
# PowerSystemResource.py
# Python implementation of the Class PowerSystemResource
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 7:21:13 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Meas.Control import Control
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Meas.Measurement import Measurement
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.PSRType import PSRType
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from CIM_STD_PYTHON.TC57CIM.IEC61968.Common.ConfigurationEvent import ConfigurationEvent

class PowerSystemResource(IdentifiedObject):
    """
    A power system resource can be an item of equipment such as a switch, an
    equipment container containing many individual items of equipment such as a
    substation, or an organisational entity such as sub-control area. Power system
    resources can have measurements associated.
    """

    def __init__(self):

        # The controller outputs used to actually govern a regulating device, e.g. the
        # magnetization of a synchronous machine or capacitor bank breaker actuator.
        super().__init__()
        self.controls = [Control()]

        # The measurements associated with this power system resource.
        self.measurements = [Measurement()]

        # Custom classification for this power system resource.
        self.psr_type = PSRType()

        self.configuration_event = ConfigurationEvent()
