#######################################################
# 
# RegularTimePoint.py
# Python implementation of the Class RegularTimePoint
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 10:05:31 PM
# 
#######################################################

class RegularTimePoint:
    """Time point for a schedule where the time between the consecutive points is
    constant.
    """
    def __init__(self):
        # The position of the regular time point in the sequence.
        # Note that time points don't have to be sequential, i.e. time points may be omitted.
        # The actual time for a RegularTimePoint is computed by multiplying the associated
        # regular interval schedule's time step with the regular time point sequence number and
        # adding the associated schedules start time.
        self.sequence_number = 0
        # The first value at the time. The meaning of the value is defined by the
        # derived type of the associated schedule.
        self.value1 = 0.0
        # The second value at the time. The meaning of the value is
        # defined by the derived type of the associated schedule.
        self.value2 = 0.0

