#######################################################
# 
# Specification.py
# Python implementation of the Class Specification
# Generated by Enterprise Architect
# Created on:      20-Dec-2023 5:41:21 PM
# 
#######################################################
from IEC61968.Assets.Medium import Medium
from IEC61968.Common.Document import Document
from IEC61968.InfIEC61968.InfAssets.AssetPropertyCurve import AssetPropertyCurve


class Specification(Document):
    """Specification can be used for various purposes relative to an asset, a logical
    device (PowerSystemResource), location, etc. Examples include documents
    supplied by manufacturers such as asset installation instructions, asset
    maintenance instructions, etc.
    """
    def __init__(self):
        super().__init__()
        self.asset_property_curves = [AssetPropertyCurve()]
        self.mediums = [Medium()]
