#######################################################
# 
# ErpBankAccount.py
# Python implementation of the Class ErpBankAccount
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 4:08:13 PM
# 
#######################################################

from CIM_STD_PYTHON.TC57CIM.IEC61968.InfIEC61968.InfCommon.BankAccount import BankAccount

class ErpBankAccount(BankAccount):
    """Relationship under a particular name, usually evidenced by a deposit against
    which withdrawals can be made. Types of bank accounts include: demand, time,
    custodial, joint, trustee, corporate, special, and regular accounts.
      A statement of transactions during a fiscal period and the resulting balance
    is maintained on each account.
      For Payment metering, the account is associated with Bank and Supplier,
    reflecting details of the bank account used for depositing revenue collected by
    TokenVendor. The name of the account holder should be specified in 'name'
    attribute.
    """
    def __init__(self):
        # Bank ABA.
        super().__init__()
        self.bank_aba = ""
