#######################################################
# 
# ErpBomItemData.py
# Python implementation of the Class ErpBomItemData
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 4:08:23 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpBOM import ErpBOM
from CIM_STD_PYTHON.TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpIdentifiedObject import ErpIdentifiedObject


class ErpBomItemData(ErpIdentifiedObject):
    """An individual item on a bill of materials.
    """

    def __init__(self):
        super().__init__()
        self.erp_bom = ErpBOM()
        self.design_location = DesignLocation()
