#######################################################
# 
# ErpChartOfAccounts.py
# Python implementation of the Class ErpChartOfAccounts
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 4:08:33 PM
# 
#######################################################
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpDocument import ErpDocument

class ErpChartOfAccounts(ErpDocument):
    """Accounting structure of a business. Each account represents a financial aspect
    of a business, such as its Accounts Payable, or the value of its inventory, or
    its office supply expenses.
    """
    pass
