#######################################################
# 
# ErpCompetency.py
# Python implementation of the Class ErpCompetency
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 4:08:56 PM
# 
#######################################################
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpIdentifiedObject import ErpIdentifiedObject

class ErpCompetency(ErpIdentifiedObject):
    """Information that describes aptitudes of a utility employee. Unlike Skills that
    an ErpPerson must be certified to perform before undertaking certain type of
    assignments (to be able to perfrom a Craft), ErpCompetency has more to do with
    typical Human Resource (HR) matters such as schooling, training, etc.
    """
    pass
