from IEC61970.Base.Domain.ActivePower import ActivePower
from IEC61970.Base.Domain.PU import PU
from IEC61970.Base.Domain.Seconds import Seconds
from IEC61970.Dynamics.StandardModels.TurbineGovernorDynamics import TurbineGovernorDynamics

class GovSteamEU(TurbineGovernorDynamics):
    """
    Simplified model of boiler and steam turbine with PID governor.
    """
    def __init__(self):
        super().__init__()
        self.chc = -3.3  # Control valves rate closing limit (Chc).  Unit = PU/sec.  Typical Value = -3.3.
        self.cho = 0.17  # Control valves rate opening limit (Cho).  Unit = PU/sec.  Typical Value = 0.17.
        self.cic = PU(-2.2)  # Intercept valves rate closing limit (Cic).  Typical Value = -2.2.
        self.cio = PU(0.123)  # Intercept valves rate opening limit (Cio).  Typical Value = 0.123.
        self.db1 = PU(0)  # Dead band of the frequency corrector (db1).  Typical Value = 0.
        self.db2 = PU(0.0004)  # Dead band of the speed governor (db2).  Typical Value = 0.0004.
        self.hhpmax = PU(1)  # Maximum control valve position (Hhpmax).  Typical Value = 1.
        self.ke = PU(0.65)  # Gain of the power controller (Ke).  Typical Value = 0.65.
        self.kfcor = PU(20)  # Gain of the frequency corrector (Kfcor).  Typical Value = 20.
        self.khp = PU(0.277)  # Fraction of total turbine output generated by HP part (Khp).  Typical Value = 0.277.
        self.klp = PU(0.723)  # Fraction of total turbine output generated by HP part (Klp).  Typical Value = 0.723.
        self.kwcor = PU(20)  # Gain of the speed governor (Kwcor).  Typical Value = 20.
        self.mwbase = ActivePower()  # Base for power values (MWbase) (>0).  Unit = MW.
        self.pmax = PU(1)  # Maximal active power of the turbine (Pmax).  Typical Value = 1.
        self.prhmax = PU(1.4)  # Maximum low pressure limit (Prhmax).  Typical Value = 1.4.
        self.simx = PU(0.425)  # Intercept valves transfer limit (Simx).  Typical Value = 0.425.
        self.tb = Seconds(100)  # Boiler time constant (Tb).  Typical Value = 100.
        self.tdp = Seconds(0)  # Derivative time constant of the power controller (Tdp).  Typical Value = 0.
        self.ten = Seconds(0.1)  # Electro hydraulic transducer (Ten).  Typical Value = 0.1.
        self.tf = Seconds(0)  # Frequency transducer time constant (Tf).  Typical Value = 0.
        self.tfp = Seconds(0)  # Time constant of the power controller (Tfp).  Typical Value = 0.
        self.thp = Seconds(0.31)  # High pressure (HP) time constant of the turbine (Thp).  Typical Value = 0.31.
        self.tip = Seconds(2)  # Integral time constant of the power controller (Tip).  Typical Value = 2.
        self.tlp = Seconds(0.45)  # Low pressure(LP) time constant of the turbine (Tlp).  Typical Value = 0.45.
        self.tp = Seconds(0.07)  # Power transducer time constant (Tp).  Typical Value = 0.07.
        self.trh = Seconds(8)  # Reheater  time constant of the turbine (Trh).  Typical Value = 8.
        self.tvhp = Seconds(0.1)  # Control valves servo time constant (Tvhp).  Typical Value = 0.1.
        self.tvip = Seconds(0.15)  # Intercept valves servo time constant (Tvip).  Typical Value = 0.15.
        self.tw = Seconds(0.02)  # Speed transducer time constant (Tw).  Typical Value = 0.02.
        self.wfmax = PU(0.05)  # Upper limit for frequency correction (Wfmax).  Typical Value
        self.wfmin = PU(-0.05)  # Lower limit for frequency correction (Wfmin).  Typical Value = -0.05.
        self.wmax1 = PU(1.025)  # Emergency speed control lower limit (wmax1).  Typical Value = 1.025.
        self.wmax2 = PU(1.05)  # Emergency speed control upper limit (wmax2).  Typical Value = 1.05.
        self.wwmax = PU(0.1)  # Upper limit for the speed governor (Wwmax).  Typical Value = 0.1.
        self.wwmin = PU(-1)  # Lower limit for the speed governor frequency correction (Wwmin).  Typical Value = -1.

