#######################################################
# 
# ErpBomItemData.py
# Python implementation of the Class ErpBomItemData
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:21 PM
# 
#######################################################
import ErpBOM
import ErpIdentifiedObject
from IEC61968 import DesignLocation

class ErpBomItemData(ErpIdentifiedObject):
    """An individual item on a bill of materials.
    """
    ErpBOM= ErpBOM()

    DesignLocation= DesignLocation()
