#######################################################
# 
# ErpBOM.py
# Python implementation of the Class ErpBOM
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:21 PM
# 
#######################################################
import ErpDocument

class ErpBOM(ErpDocument):
    """Information that generally describes the Bill of Material Structure and its
    contents for a utility.
    
      This is used by ERP systems to transfer Bill of Material information between
    two business applications.
    """
    pass
