#######################################################
# 
# ErpCompetency.py
# Python implementation of the Class ErpCompetency
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:21 PM
# 
#######################################################
import ErpIdentifiedObject

class ErpCompetency(ErpIdentifiedObject):
    """Information that describes aptitudes of a utility employee. Unlike Skills that
    an ErpPerson must be certified to perform before undertaking certain type of
    assignments (to be able to perfrom a Craft), ErpCompetency has more to do with
    typical Human Resource (HR) matters such as schooling, training, etc.
    """
    pass
