#######################################################
# 
# ErpChartOfAccounts.py
# Python implementation of the Class ErpChartOfAccounts
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:21 PM
# 
#######################################################
import ErpDocument

class ErpChartOfAccounts(ErpDocument):
    """Accounting structure of a business. Each account represents a financial aspect
    of a business, such as its Accounts Payable, or the value of its inventory, or
    its office supply expenses.
    """
    pass
