#######################################################
# 
# BlockDispatchOrder.py
# Python implementation of the Class BlockDispatchOrder
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:56:48 PM
# Original author: selaost1
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.ActivePower import ActivePower
# from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Integer import Integer
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.EnergyArea.BlockDispatchComponent import BlockDispatchComponent
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class BlockDispatchOrder(IdentifiedObject):

    def __init__(self):
        super().__init__()
        self.m_block_dispatch_component = BlockDispatchComponent()
