#######################################################
# 
# BlockDispatchInstruction.py
# Python implementation of the Class BlockDispatchInstruction
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:56:13 PM
# Original author: selaost1
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.EnergyArea.EnergyGroup import EnergyGroup
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.EnergyArea.BlockDispatchOrder import BlockDispatchOrder

class BlockDispatchInstruction(IdentifiedObject):

    def __init__(self):
        super().__init__()
        self.m_energy_group = EnergyGroup()
        self.m_block_dispatch_order = BlockDispatchOrder()
