#######################################################
# 
# BlockDispatchComponent.py
# Python implementation of the Class BlockDispatchComponent
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:55:54 PM
# Original author: selaost1
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.EnergyArea.EnergyComponent import EnergyComponent

class BlockDispatchComponent(EnergyComponent):
    def __init__(self):
        super().__init__()

