#######################################################
# 
# EnergySchedulingArea.py
# Python implementation of the Class EnergySchedulingArea
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:52:27 PM
# Original author: selaost1
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.ActivePower import ActivePower
# from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Float import Float
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.EnergyArea.EnergyAreaTypeKind import EnergyAreaTypeKind
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.EnergyArea.EnergySchedulingAreaBoundary import EnergySchedulingAreaBoundary
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.PowerSystemResource import PowerSystemResource


class EnergySchedulingArea(PowerSystemResource):

    def __init__(self):
        super().__init__()
        self.m_energy_scheduling_area_boundary = EnergySchedulingAreaBoundary()
