#######################################################
# 
# EnergyTypeReference.py
# Python implementation of the Class EnergyTypeReference
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:51:54 PM
# Original author: selaost1
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.EnergyArea.EnergyTypeKind import EnergyTypeKind
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class EnergyTypeReference(IdentifiedObject):

    def __init__(self):
        super().__init__()

