#######################################################
# 
# EnergyTypeReference.py
# Python implementation of the Class EnergyTypeReference
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:51:54 PM
# Original author: selaost1
#######################################################
from IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class EnergyTypeReference(IdentifiedObject):

    def __init__(self):
        super().__init__()

