#######################################################
# 
# EnergyGroup.py
# Python implementation of the Class EnergyGroup
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:49:46 PM
# Original author: selaost1
# 
#######################################################
# from IEC61970.Base.Domain.Boolean import Boolean
from IEC61970.Base.Domain.ActivePower import ActivePower
from IEC61970.InfIEC61970.EnergyArea.EnergyTypeReference import EnergyTypeReference
from IEC61970.InfIEC61970.EnergyArea.EnergySchedulingArea import EnergySchedulingArea
from IEC61970.Base.Core.PowerSystemResource import PowerSystemResource


class EnergyGroup(PowerSystemResource):

    def __init__(self):
        super().__init__()
        self.m_energy_type_reference= EnergyTypeReference()

        self.m_energy_scheduling_area= EnergySchedulingArea()
