#######################################################
# 
# EnergySchedulingAreaBoundary.py
# Python implementation of the Class EnergySchedulingAreaBoundary
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:54:46 PM
# Original author: selaost1
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class EnergySchedulingAreaBoundary(IdentifiedObject):

    def __init__(self):
        super().__init__()

