#######################################################
# 
# EnergyTypeKind.py
# Python implementation of the Class EnergyTypeKind
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:55:40 PM
# Original author: selaost1
# 
#######################################################


class EnergyTypeKind:

    def __init__(self):
        pass