#######################################################
# 
# EnergyAreaTypeKind.py
# Python implementation of the Class EnergyAreaTypeKind
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:55:24 PM
# Original author: selaost1
# 
#######################################################


class EnergyAreaTypeKind:

    def __init__(self):
        pass
