#######################################################
# 
# ProportionalDistributionComponent.py
# Python implementation of the Class ProportionalDistributionComponent
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:55:07 PM
# Original author: selaost1
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.ActivePower import ActivePower
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.EnergyArea.EnergyComponent import EnergyComponent

class ProportionalDistributionComponent(EnergyComponent):

    def __init__(self):
        super().__init__()

