#######################################################
# 
# MeasurementValueQualityExt.py
# Python implementation of the Class MeasurementValueQualityExt
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:00 PM
# Original author: SELAOST1
# 
#######################################################


class MeasurementValueQualityExt:
    pass
