#######################################################
# 
# MeasurementConfigurationStatus.py
# Python implementation of the Class MeasurementConfigurationStatus
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:32:00 PM
# Original author: selaost1
# 
#######################################################


class MeasurementConfigurationStatus:
    pass
