#######################################################
# 
# Classification.py
# Python implementation of the Class Classification
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 9:57:58 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol
# from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Integer import Integer


class Classification:
    """Classification of level.  Specify as 1..n, with 1 being the most detailed,
    highest priority, etc as described on the attribue using this data type.
    """
    unit = UnitSymbol.none

    def __init__(self):
        self.multiplier = UnitMultiplier.none
        self.value = 0.0
