#######################################################
# 
# GeneratorControlMode.py
# Python implementation of the Class GeneratorControlMode
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 9:52:39 PM
# 
#######################################################
from enum import Enum


class GeneratorControlMode(Enum):
    """Unit control modes.
    """
    SET_POINT = 0
    PULSE = 1
