#######################################################
# 
# HydroPumpOpSchedule.py
# Python implementation of the Class HydroPumpOpSchedule
# Generated by Enterprise Architect
# Created on:      18-Dec-2023 1:24:25 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.RegularIntervalSchedule import RegularIntervalSchedule


class HydroPumpOpSchedule(RegularIntervalSchedule):
    """The hydro pump's Operator-approved current operating schedule (or plan),
    typically produced with the aid of unit commitment type analyses.The unit's
    operating schedule status is typically given as: (0=unavailable) (1=avilable to
    startup or shutdown)  (2=must pump).
    """
    def __init__(self):
        super().__init__()

