#######################################################
# 
# HydroPump.py
# Python implementation of the Class HydroPump
# Generated by Enterprise Architect
# Created on:      18-Dec-2023 1:19:17 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.VolumeFlowRate import VolumeFlowRate
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.ActivePower import ActivePower
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.Equipment import Equipment
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Generation.Production.HydroPumpOpSchedule import HydroPumpOpSchedule

class HydroPump(Equipment):
    """A synchronous motor-driven pump, typically associated with a pumped storage
    plant.
    """

    def __init__(self):
        super().__init__()
        self.pump_disch_at_max_head = VolumeFlowRate()
        self.pump_disch_at_min_head = VolumeFlowRate()
        self.pump_power_at_max_head = ActivePower()
        self.pump_power_at_min_head = ActivePower()
        self.hydro_pump_op_schedule = HydroPumpOpSchedule()  # The hydro pump has a pumping schedule over time,
        # indicating when pumping is to occur.