#######################################################
# 
# WindGenUnitKind.py
# Python implementation of the Class WindGenUnitKind
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 10:25:50 PM
# 
#######################################################
from enum import Enum


class WindGenUnitKind(Enum):
    """Kind of wind generating unit.
    """
    OFFSHORE = 0
    ONSHORE = 1
