#######################################################
# 
# BankAccount.py
# Python implementation of the Class BankAccount
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:19 PM
# Original author: T. Kostic
# 
#######################################################
from java.IEC61968.InfIEC61968.InfCommon.Bank import Bank
from java.IEC61968.Common import Document

class BankAccount(Document):
    """Bank account.
    """
    # Bank that provides this BankAccount.
    Bank= Bank()
