#######################################################
# 
# Bank.py
# Python implementation of the Class Bank
# Generated by Enterprise Architect
# Created on:      25-Dec-2023 8:45:19 PM
# 
#######################################################
from java.IEC61968.Common.OrganisationRole import OrganisationRole

class Bank(OrganisationRole):
    """Organisation that is a commercial bank, agency, or other institution that
    offers a similar service.
    """
    pass
