#######################################################
# 
# DocumentPersonRole.py
# Python implementation of the Class DocumentPersonRole
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 1:29:02 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61968.Common.PersonRole import PersonRole


class DocumentPersonRole(PersonRole):
    """Person role with respect to documents.
    """
    def __init__(self):
        super().__init__()

