#######################################################
# 
# TimeSchedule.py
# Python implementation of the Class TimeSchedule
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 8:55:25 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61968.Common.Document import Document
from CIM_STD_PYTHON.TC57CIM.IEC61968.Common.TimePoint import TimePoint
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.DateTimeInterval import DateTimeInterval
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Seconds import Seconds


class TimeSchedule(Document):
    """Description of anything that changes through time. Time schedule is used to
    perform a single-valued function of time. Use inherited 'type' attribute to
    give additional information on this schedule, such as: periodic (hourly, daily,
    weekly, monthly, etc.), day of the month, by date, calendar (specific times and
    dates).
    """

    def __init__(self):
        super().__init__()
        self.diabled = True
        self.offset = Seconds()
        self.recurrence_pattern = ""
        self.recurrence_period = Seconds()
        self.time_points = [TimePoint()]  # Sequence of time points belonging to this time schedule.
        self.schedule_interval = DateTimeInterval()
