#######################################################
# 
# TimePoint.py
# Python implementation of the Class TimePoint
# Generated by Enterprise Architect
# Created on:      19-Dec-2023 9:00:24 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61968.Common.Status import Status
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.DateTimeInterval import DateTimeInterval
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Seconds import Seconds


class TimePoint(IdentifiedObject):
    """A point in time within a sequence of points in time relative to a time schedule.
    """
    pass

    def __init__(self):
        super().__init__()
        self.daet_time = DateTime()
        self.relative_time_interval = Seconds()
        self.sequence_number = 0
        self.status = Status()
        self.window = DateTimeInterval()
